/*
 * File: app/view/FarmGZN/Edit.js
 * Date: Wed Jan 31 2018 12:25:20 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.FarmGZN.Edit', {
  extend: 'Ext.window.Window',
  alias: 'widget.farmgzn.edit',

  requires: [
    'Portal.view.FarmGZN.EditViewModel',
    'Portal.view.FarmGZN.EditViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.FieldSet',
    'Ext.form.field.ComboBox',
    'Ext.form.field.Date',
    'Ext.form.field.Number',
    'Ext.form.field.Checkbox',
    'Ext.form.field.Hidden'
  ],

  controller: 'farmgzn.edit',
  viewModel: {
    type: 'farmgzn.edit'
  },
  modal: true,
  height: 496,
  width: 727,
  layout: 'fit',
  title: 'КН:',
  maximizable: true,

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      scrollable: true,
      bodyPadding: 10,
      url: 'data/FarmGZN/Data-edit.php',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              formBind: true,
              reference: 'Save',
              iconCls: 'dialog-save',
              text: 'Сохранить',
              listeners: {
                click: 'onSave'
              }
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'fieldset',
          title: 'Земельный участок',
          items: [
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Кадастровый номер',
              labelWidth: 120,
              name: 'cad_num',
              allowBlank: false
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Адрес',
              labelWidth: 50,
              name: 'address',
              allowBlank: false
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Мероприятие по ГЗН',
          items: [
            {
              xtype: 'combobox',
              anchor: '100%',
              fieldLabel: 'Орган, проводивший проверку',
              labelWidth: 200,
              name: 'otdel',
              allowBlank: false,
              editable: false,
              autoLoadOnValue: true,
              displayField: 'name',
              valueField: 'id',
              bind: {
                store: '{organ1}'
              }
            },
            {
              xtype: 'combobox',
              anchor: '100%',
              fieldLabel: 'Мероприятие',
              name: 'job',
              allowBlank: false,
              editable: false,
              autoLoadOnValue: true,
              displayField: 'name',
              valueField: 'id',
              bind: {
                store: '{jobs}'
              }
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Проверка',
          items: [
            {
              xtype: 'fieldset',
              title: 'Форма проведения проверки',
              layout: {
                type: 'hbox',
                align: 'stretchmax',
                pack: 'center'
              },
              items: [
                {
                  xtype: 'container',
                  flex: 1,
                  layout: 'form',
                  items: [
                    {
                      xtype: 'combobox',
                      flex: 1,
                      name: 'prov_form_1',
                      editable: false,
                      autoLoadOnValue: true,
                      displayField: 'name',
                      valueField: 'id',
                      bind: {
                        store: '{prov_form_1}'
                      }
                    },
                    {
                      xtype: 'combobox',
                      name: 'prov_form_2',
                      editable: false,
                      autoLoadOnValue: true,
                      displayField: 'name',
                      valueField: 'id',
                      bind: {
                        store: '{prov_form_2}'
                      }
                    }
                  ]
                },
                {
                  xtype: 'container',
                  layout: 'form',
                  items: [
                    {
                      xtype: 'datefield',
                      disabled: true,
                      fieldLabel: 'Дата начала',
                      name: 'prov_date_begin',
                      format: 'Y-m-d'
                    },
                    {
                      xtype: 'datefield',
                      fieldLabel: 'Дата окончания',
                      name: 'prov_date_end',
                      format: 'Y-m-d'
                    }
                  ]
                }
              ]
            },
            {
              xtype: 'fieldset',
              title: 'Акт проведения проверки',
              layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
              },
              items: [
                {
                  xtype: 'datefield',
                  padding: '0 5 5 0',
                  fieldLabel: 'Дата',
                  labelWidth: 50,
                  name: 'prov_akt_date',
                  format: 'Y-m-d'
                },
                {
                  xtype: 'textfield',
                  flex: 1,
                  padding: '0 5 5 5',
                  fieldLabel: 'Номер',
                  labelWidth: 50,
                  name: 'prov_akt_num'
                }
              ]
            },
            {
              xtype: 'fieldset',
              title: 'Предписание об устранении нарушений',
              layout: {
                type: 'hbox',
                align: 'stretch'
              },
              items: [
                {
                  xtype: 'datefield',
                  padding: '0 5 5 0',
                  fieldLabel: 'Дата',
                  labelWidth: 50,
                  name: 'prov_pred_date',
                  format: 'Y-m-d'
                },
                {
                  xtype: 'textfield',
                  flex: 1,
                  padding: '0 5 5 5',
                  fieldLabel: 'Номер',
                  labelWidth: 50,
                  name: 'prov_pred_num'
                },
                {
                  xtype: 'datefield',
                  padding: '0 5 5 5',
                  fieldLabel: 'Срок',
                  labelWidth: 50,
                  name: 'prov_pred_srok',
                  format: 'Y-m-d'
                }
              ]
            },
            {
              xtype: 'container',
              layout: {
                type: 'hbox',
                align: 'stretch'
              },
              items: [
                {
                  xtype: 'container',
                  items: [
                    {
                      xtype: 'numberfield',
                      fieldLabel: 'Площадь нарушения, кв.м',
                      labelAlign: 'top',
                      name: 'area',
                      minValue: 0
                    }
                  ]
                },
                {
                  xtype: 'container',
                  flex: 1,
                  layout: 'form',
                  items: [
                    {
                      xtype: 'textfield',
                      fieldLabel: 'Вид нарушения',
                      name: 'error_vid'
                    },
                    {
                      xtype: 'textfield',
                      fieldLabel: 'Оборот',
                      name: 'oborot'
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Устранение нарушения',
          items: [
            {
              xtype: 'checkboxfield',
              name: 'error_type',
              boxLabel: 'Нарушение устранено'
            },
            {
              xtype: 'combobox',
              anchor: '100%',
              fieldLabel: 'Орган, принявший решение',
              labelWidth: 170,
              name: 'organ',
              autoLoadOnValue: true,
              displayField: 'name',
              valueField: 'id',
              bind: {
                store: '{organ2}'
              }
            },
            {
              xtype: 'fieldset',
              title: 'Документ об устранении',
              layout: {
                type: 'hbox',
                align: 'stretch'
              },
              items: [
                {
                  xtype: 'datefield',
                  padding: '0 5 5 0',
                  fieldLabel: 'Дата',
                  labelWidth: 50,
                  name: 'edoc_date',
                  format: 'Y-m-d'
                },
                {
                  xtype: 'textfield',
                  flex: 1,
                  padding: '0 5 5 5.',
                  fieldLabel: 'Номер',
                  labelWidth: 50,
                  name: 'edoc_num'
                }
              ]
            }
          ]
        },
        {
          xtype: 'hiddenfield',
          anchor: '100%',
          fieldLabel: 'Label',
          name: 'id'
        }
      ]
    }
  ]

});