/*
 * File: app/view/CadastErrors/DataIn.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.CadastErrors.DataIn', {
  extend: 'Ext.window.Window',
  alias: 'widget.cadasterrors.datain',

  requires: [
    'Portal.view.CadastErrors.DataInViewModel',
    'Portal.view.CadastErrors.DataInViewController',
    'Ext.toolbar.Toolbar',
    'Ext.form.field.Date',
    'Ext.form.field.ComboBox',
    'Ext.XTemplate',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.grid.column.Number',
    'Ext.form.field.Number',
    'Ext.view.Table',
    'Ext.grid.plugin.CellEditing'
  ],

  controller: 'cadasterrors.datain',
  viewModel: {
    type: 'cadasterrors.datain'
  },
  modal: true,
  height: 330,
  width: 657,
  layout: 'fit',
  title: 'Данные по кадастровому инженеру',
  maximizable: true,
  defaultListenerScope: true,

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'datefield',
          reference: 'dateIn',
          fieldLabel: 'На дату',
          labelWidth: 50,
          format: 'Y-m-d',
          listeners: {
            change: {
              fn: 'onDateInChange',
              scope: 'controller'
            }
          }
        },
        {
          xtype: 'combobox',
          flex: 1,
          reference: 'engineer',
          editable: false,
          emptyText: 'Кадастровый инженер',
          autoLoadOnValue: true,
          displayField: 'fio',
          displayTpl: [
            '<tpl for=".">',
            '  {fio} => {AttNumber}',
            '</tpl>'
          ],
          valueField: 'id',
          bind: {
            store: '{engineers}'
          },
          listeners: {
            change: {
              fn: 'onEngChange',
              scope: 'controller'
            }
          }
        },
        {
          xtype: 'button',
          reference: 'btnSay',
          disabled: true,
          iconCls: 'icon-say',
          text: 'Покажись',
          listeners: {
            click: {
              fn: 'onSay',
              scope: 'controller'
            }
          }
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      reference: 'grid',
      disabled: true,
      bind: {
        store: '{datas}'
      },
      columns: [
        {
          xtype: 'rownumberer'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          text: 'Параметр',
          columns: [
            {
              xtype: 'gridcolumn',
              width: 180,
              dataIndex: 'GR',
              text: 'Группа'
            },
            {
              xtype: 'gridcolumn',
              flex: 1,
              dataIndex: 'NAME',
              text: 'Наименование'
            }
          ]
        },
        {
          xtype: 'numbercolumn',
          align: 'end',
          dataIndex: 'var_data',
          text: 'Значение',
          editor: {
            xtype: 'numberfield'
          }
        }
      ],
      plugins: [
        {
          ptype: 'cellediting',
          listeners: {
            edit: 'onCellEditingEdit'
          }
        }
      ]
    }
  ],
  listeners: {
    afterrender: {
      fn: 'onAfterRender',
      scope: 'controller'
    }
  },

  onCellEditingEdit: function(editor, context, eOpts) {
    var //d=this.getReferences().dateParams.getValue(),
    s=this.getViewModel().getStore('datas');
    //console.log(context.record.data);
    Ext.Ajax.request({
      url: 'data/CadastErrors/Data-edit.php',
      params: {
        action:"edit",
        id:context.record.data.id,
        var_data:context.record.data.var_data
      },
      success: function(r) {
        s.reload();
      }
    });
  }

});