/*
 * File: app/view/Deads/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.Deads.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.deadsmain',

  requires: [
    'Portal.view.Deads.mainViewModel',
    'Portal.view.Deads.mainViewController',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.Date',
    'Ext.grid.filters.filter.Date',
    'Ext.view.Table',
    'Ext.form.field.Text',
    'Ext.grid.filters.Filters',
    'Ext.toolbar.Paging'
  ],

  controller: 'deads.main',
  viewModel: {
    type: 'deads.main'
  },
  height: 311,
  width: 547,
  layout: 'fit',
  title: 'My Panel',

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'button',
          reference: 'btLoadFile',
          text: 'Загрузить файл',
          listeners: {
            click: 'onImportClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'icon-refresh',
          listeners: {
            click: 'onRefreshClick'
          }
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      store: 'Deads.main',
      columns: [
        {
          xtype: 'gridcolumn',
          flex: 1,
          dataIndex: 'FIO',
          text: 'Ф.И.О.'
        },
        {
          xtype: 'datecolumn',
          dataIndex: 'DR',
          text: 'Дата рождения',
          format: 'Y-m-d',
          filter: {
            type: 'date'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'MR',
          text: 'Место рождения'
        },
        {
          xtype: 'datecolumn',
          width: 82,
          dataIndex: 'Period1',
          text: 'Дата смерти',
          format: 'Y-m-d',
          filter: {
            type: 'date'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'Place',
          text: 'ЗАГС'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'textfield',
              flex: 1,
              name: 'seek',
              emptyText: 'Поиск по Ф.И.О.',
              enableKeyEvents: true,
              listeners: {
                change: 'onSeekChange'
              }
            }
          ]
        },
        {
          xtype: 'pagingtoolbar',
          dock: 'bottom',
          width: 360,
          displayInfo: true,
          store: 'Deads.main'
        }
      ],
      plugins: [
        {
          ptype: 'gridfilters'
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onPanelAfterRender'
  }

});