/*
 * File: app/store/Deads/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.Deads.main', {
  extend: 'Ext.data.Store',

  requires: [
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.field.Date'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'Deads.main',
      proxy: {
        type: 'ajax',
        url: 'data/Deads/main.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'FIO'
        },
        {
          type: 'date',
          name: 'DR'
        },
        {
          name: 'MR'
        },
        {
          type: 'date',
          name: 'Period1'
        },
        {
          type: 'date',
          name: 'Period2'
        },
        {
          name: 'Place'
        }
      ]
    }, cfg)]);
  }
});