/*
 * File: app/view/LoadUpr/InputTimesViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.InputTimesViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.loadupr.inputtimes',

  onYearChange: function(field, newValue, oldValue, eOpts) {
    Ext.getStore("LoadUpr.Months").load({params:{mode:'0',years:newValue,list:'short2'}});
    this.getReferences().cbMonth.setDisabled(false);
  },

  onMonthChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences(),Y=r.cbYear.getValue();
    r.PeriodClose.setDisabled(false);
    r.tbTime.setDisabled(false);
    Ext.getStore('LoadUpr.Times').load({params:{mode:'0',years:Y,months:newValue}});
  },

  onPeriodCloseClick: function(button, e, eOpts) {
    var me=this,r=me.getReferences(),Y=r.cbYear.getValue(),M=r.cbMonth.getValue();
    Ext.Msg.show({
      title:'Закрыть данный период?',
      message:'Если закрыть данный период, то никакие изменения больше нельзя будет внести.<br>Вы уверены, что желаете закрыть данный период?',
      buttons:Ext.Msg.YESNOCANCEL,
      icon:Ext.Msg.QUESTION,
      fn:function(btn){
        if(btn==='yes'){
          Ext.Ajax.request({
            url:'data/LoadUpr/PeriodClose.php',
            params:{mode:"close",years:Y,months:M},
            success:function(r,o){me.getView().close();},
            failure:function(r,o){console.log(r.status);}
          });
        }
      }
    });
  },

  onWindowAfterRender: function(component, eOpts) {
    this.getReferences().tbTime.setDisabled(true);
  }

});
