/*
 * File: app/view/LoadUpr/mainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.mainViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.loadupr.main',

  onYearChange: function(field, newValue, oldValue, eOpts) {
    Ext.getStore("LoadUpr.Months").load({params:{mode:"A",years:newValue,list:'short2'}});
    var r=this.getReferences(),M=r.cbMonth;
    M.clearValue();
    M.setDisabled(false);
    r.grid.setDisabled(true);
    r.btSay.setDisabled(true);
  },

  onMonthChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences();
    if(newValue===''){r.grid.setDisabled(true);r.btSay.setDisabled(true);}else{r.btSay.setDisabled(false);}

  },

  onSayClick: function(button, e, eOpts) {
    var r=this.getReferences(),Y=r.cbYear.getValue(),M=r.cbMonth.getValue();
    r.grid.setDisabled(false);
    Ext.getStore("LoadUpr.main").load({params:{years:Y,months:M}});
  },

  onMainDataClick: function(button, e, eOpts) {
    Ext.create('Portal.view.LoadUpr.InputData').show();
  },

  onReferClick: function(button, e, eOpts) {
    window.open('http://10.51.118.210/advanced/frontend/web/index.php?r=site%2Fpage&view=nagruzka','_blank');
  },

  onTimesClick: function(button, e, eOpts) {
    Ext.create('Portal.view.LoadUpr.InputTimes').show();
  },

  onAfterRender: function(component, eOpts) {
    var AccessEdit = Portal.util.Util.appAccessEdit(this.getView().xtype),ref=this.getReferences();
    console.log('AccessEdit='+AccessEdit);
    ref.btTimes.setHidden(!AccessEdit);
    //var td=new Date();
    //this.getReferences().cbYear.setValue(td.getFullYear());
  }

});
