/*
 * File: app/view/HW_PC/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.HW_PC.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.hw_pcmain',

  requires: [
    'Portal.view.HW_PC.mainViewModel',
    'Portal.view.HW_PC.mainViewController',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.grid.filters.filter.String',
    'Ext.grid.column.Date',
    'Ext.grid.filters.filter.Date',
    'Ext.grid.column.Number',
    'Ext.grid.filters.filter.Number',
    'Ext.view.Table',
    'Ext.grid.feature.Grouping',
    'Ext.grid.filters.Filters',
    'Ext.XTemplate'
  ],

  controller: 'hw_pc.main',
  viewModel: {
    type: 'hw_pc.main'
  },
  autoShow: true,
  height: 458,
  width: 603,
  layout: 'border',
  title: 'My Window',

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'button',
          text: 'Обработать каталог',
          listeners: {
            click: 'onGetXmlClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'icon-refresh',
          text: 'Обновить',
          listeners: {
            click: 'onRefreshClick'
          }
        },
        {
          xtype: 'button',
          reference: 'btnDel',
          disabled: true,
          iconCls: 'icon-delete',
          text: 'Удалить',
          listeners: {
            click: 'onDeleteClick'
          }
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      region: 'center',
      split: true,
      reference: 'mainGrid',
      bind: {
        store: '{main}'
      },
      columns: [
        {
          xtype: 'rownumberer'
        },
        {
          xtype: 'gridcolumn',
          width: 120,
          dataIndex: 'DNSHostName',
          text: 'Сетевое имя',
          filter: {
            type: 'string'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'IPAddress',
          text: 'IPaddress',
          filter: {
            type: 'string'
          }
        },
        {
          xtype: 'gridcolumn',
          text: 'Последний вход в систему',
          columns: [
            {
              xtype: 'datecolumn',
              width: 80,
              dataIndex: 'HDate',
              text: 'Дата',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              width: 80,
              dataIndex: 'HTime',
              text: 'Время'
            },
            {
              xtype: 'gridcolumn',
              width: 130,
              dataIndex: 'UserName',
              text: 'Пользователь',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'UName',
              width: 226,
              text: 'ФИО',
              filter: {
                type: 'string'
              }
            }
          ]
        },
        {
          xtype: 'gridcolumn',
          width: 133,
          dataIndex: 'Manufacturer',
          text: 'Производитель'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'Model',
          text: 'Модель MB'
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'TotalPhysicalMemory',
          text: 'Всего<br>оперативки',
          filter: {
            type: 'number'
          }
        }
      ],
      listeners: {
        selectionchange: 'onGridSelectionChange'
      },
      features: [
        {
          ftype: 'grouping'
        }
      ],
      plugins: [
        {
          ptype: 'gridfilters'
        }
      ]
    },
    {
      xtype: 'panel',
      region: 'south',
      split: true,
      reference: 'DetailInfo',
      height: 190,
      scrollable: true,
      tpl: [
        '{id}'
      ],
      title: 'Детальная информация'
    }
  ],
  listeners: {
    afterrender: 'onAfterRender'
  }

});