/*
 * File: app/view/portal/admin_group.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.portal.admin_group', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.portaladmin_group',

    requires: [
        'Portal.view.portal.admin_groupViewModel',
        'Portal.view.portal.admin_groupViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.grid.column.Date',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Check'
    ],

    controller: 'portaladmin_group',
    viewModel: {
        type: 'portaladmin_group'
    },
    autoShow: true,
    height: 354,
    width: 614,
    layout: 'border',
    title: '',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            items: [
                {
                    xtype: 'panel',
                    id: 'tabAdminGroupTab1',
                    layout: 'fit',
                    title: 'Основные группы',
                    items: [
                        {
                            xtype: 'gridpanel',
                            header: false,
                            title: 'My Grid Panel',
                            store: 'admin_group.group_main',
                            columns: [
                                {
                                    xtype: 'rownumberer',
                                    width: 28
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'fio',
                                    text: 'Пользователь',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'main_group_name',
                                    text: 'Основная группа'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        switch(value){
                                            case '1':this.items[0].altText='Администратор';
                                            this.items[0].iconCls='icon-admins';
                                            this.items[0].tooltip='Администратор';
                                            break;
                                            case '2':this.items[0].altText='Пользователь';
                                            this.items[0].iconCls='icon-tick-3';
                                            this.items[0].tooltip='Пользователь';
                                            break;
                                            case '3':this.items[0].altText='Гость';
                                            this.items[0].iconCls='icon-ahtung-red';
                                            this.items[0].tooltip='Гость';
                                            break;
                                        }
                                    },
                                    dataIndex: 'main_group',
                                    width: 30,
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                //view.mask('Подождите...');
                                                Ext.Ajax.request({
                                                    url: 'data/admin_group/group_main_change.php',
                                                    params: {
                                                        id: record.data.id
                                                    },
                                                    success: function(response){
                                                        Ext.getStore('admin_group.group_main').reload();
                                                    }
                                                });
                                                //view.unmask();
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: {
                            fn: 'onTabAdminGroupTab1Activate',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'panel',
                    id: 'tabAdminGroupAppAccess',
                    layout: 'border',
                    title: 'Группы пользователей',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            reference: 'admingrid1',
                            id: 'admingroupgrid1',
                            title: '',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    hidden: true,
                                    itemId: 'mydatecolumn',
                                    dataIndex: 'date',
                                    text: 'Date'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    hidden: true,
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbAdminGroupAppAccess',
                                            fieldLabel: 'Основная группа',
                                            displayField: 'name',
                                            store: 'admin_group.group_main_list',
                                            valueField: 'id',
                                            listeners: {
                                                change: {
                                                    fn: 'onCmbAdminGroupAppAccessChange',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: {
                            fn: 'onTabAdminGroupAppAccessActivate',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'panel',
                    id: 'tabAdminGroupRightGr',
                    layout: 'border',
                    title: 'Права групп приложений',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'west',
                            split: true,
                            reference: 'admin_group_groups_app',
                            id: 'admin_group_groups',
                            width: 296,
                            title: 'Группы приложений',
                            store: 'admin_group.group_app',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id',
                                    text: 'id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 200,
                                    dataIndex: 'name',
                                    text: 'название'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'reference',
                                    text: 'Описание',
                                    tooltip: 'Описание',
                                    flex: 1
                                }
                            ],
                            listeners: {
                                select: {
                                    fn: 'onAdmin_group_groupsSelect',
                                    scope: 'controller'
                                },
                                selectionchange: 'onAdmin_group_groupsSelectionChange',
                                itemdblclick: {
                                    fn: 'onAdmin_group_groupsItemDblClick',
                                    scope: 'controller'
                                }
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            id: 'btnAdminGroupGroupAdd',
                                            text: 'Добавить',
                                            listeners: {
                                                click: {
                                                    fn: 'onBtnAdminGroupGroupAddClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnAdminGroupGroupDel',
                                            disabled: true,
                                            id: 'btnAdminGroupGroupDel',
                                            text: 'Удалить',
                                            listeners: {
                                                click: {
                                                    fn: 'onBtnAdminGroupGroupDelClick',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            id: 'admin_group_lavels',
                            title: 'Права группы на приложения',
                            store: 'admin_group.lavels',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_app',
                                    text: 'id_app'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'id_group',
                                    text: 'id_group'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name',
                                    text: 'Приложение',
                                    flex: 1
                                },
                                {
                                    xtype: 'checkcolumn',
                                    width: 60,
                                    dataIndex: 'read',
                                    text: 'чтение'
                                },
                                {
                                    xtype: 'checkcolumn',
                                    width: 60,
                                    dataIndex: 'write',
                                    text: 'запись'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: 'onTabAdminGroupRightGrActivate'
                    }
                }
            ]
        }
    ],

    onAdmin_group_groupsSelectionChange: function(model, selected, eOpts) {
        this.getReferences().btnAdminGroupGroupDel.setDisabled(selected.length === 0);
    },

    onTabAdminGroupRightGrActivate: function(component, eOpts) {
        Ext.getStore('admin_group.group_app').load();
    }

});