/*
 * File: app/view/sys/jcal/loadfileViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.jcal.loadfileViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sysjcalloadfile',

    onButtonClick: function(button, e, eOpts) {
        var me = this,
            form = me.lookupReference('Form'),
            values = form.getValues(),
            store = Ext.getStore('sys.jcal.holidays');

        if (form.isValid()) {
            form.submit({
                url: 'data/sys/jcal/jcal-edit.php',
                target : '_blank',
                waitMsg: 'Загружаю документ...',
                success: function(fp,o) {
                    console.log(o.result);
                    store.load({params:{year:2016}});
                    me.getView().close();
                },
                failure: function(fp,o) {
                    console.log(fp);
                    console.log(o.result);
                    store.load({params:{year:2016}});
                    me.getView().close();
                }
            });
        }
    }

});
