/*
 * File: app/view/sys/jcal/loadfile.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.jcal.loadfile', {
    extend: 'Ext.window.Window',
    alias: 'widget.sysjcalloadfile',

    requires: [
        'Portal.view.sys.jcal.loadfileViewModel',
        'Portal.view.sys.jcal.loadfileViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.File'
    ],

    controller: 'sysjcalloadfile',
    viewModel: {
        type: 'sysjcalloadfile'
    },
    modal: true,
    height: 134,
    width: 400,
    layout: 'fit',
    title: 'My Window',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            reference: 'Form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'container',
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Загрузить',
                                    listeners: {
                                        click: {
                                            fn: 'onButtonClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: 'Отмена',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'filefield',
                    anchor: '100%',
                    name: 'xml',
                    allowBlank: false
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        this.close();
    }

});