/*
 * File: app/view/sys/jcal/mainViewModel.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.jcal.mainViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.sysjcalmain',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        years: {
            autoLoad: false,
            proxy: {
                type: 'ajax',
                url: 'data/sys/jcal/years-list.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'c_year'
                }
            ]
        },
        days: {
            proxy: {
                type: 'ajax',
                url: 'data/sys/jcal/days-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'c_year'
                },
                {
                    name: 'c_date'
                },
                {
                    name: 'c_typeday'
                },
                {
                    name: 'c_holiday'
                }
            ]
        }
    }

});