/*
 * File: app/view/sys/jcal/main.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.jcal.main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sysjcalmain',

    requires: [
        'Portal.view.sys.jcal.mainViewModel',
        'Portal.view.sys.jcal.mainViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.Label',
        'Ext.form.Panel'
    ],

    controller: 'sysjcalmain',
    viewModel: {
        type: 'sysjcalmain'
    },
    height: 400,
    width: 586,
    layout: 'border',
    title: 'My Panel',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            split: true,
            title: 'Список праздников в году',
            store: 'sys.jcal.holidays',
            columns: [
                {
                    xtype: 'datecolumn',
                    width: 80,
                    dataIndex: 'c_date',
                    text: 'Дата',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'gridcolumn',
                    width: 116,
                    dataIndex: 'typeday',
                    text: 'Тип дня'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'holiday',
                    text: 'Название праздника'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 96,
                            name: 'cmbYear',
                            displayField: 'c_year',
                            valueField: 'c_year',
                            bind: {
                                store: '{years}'
                            },
                            listeners: {
                                change: {
                                    fn: 'onComboboxChange',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Добавить'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Удалить'
                        },
                        {
                            xtype: 'button',
                            text: 'Загрузить',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'label',
                            html: '<a href="http://xmlcalendar.ru/" target="_blank">Ссылка на сайт</a>'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'form',
            region: 'south',
            split: true,
            height: 150,
            bodyPadding: 10,
            title: 'My Form'
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.sys.jcal.loadfile').show();
    }

});