/*
 * File: app/view/Deads/mainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.Deads.mainViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.deads.main',

  onImportClick: function(button, e, eOpts) {
    Ext.create('Portal.view.Deads.File').show();
  },

  onRefreshClick: function(button, e, eOpts) {
    Ext.getStore('Deads.main').reload();
  },

  onSeekChange: function(field, newValue, oldValue, eOpts) {
    Ext.getStore('Deads.main').loadPage(1,{params:{
    FIO:newValue}});
  },

  onPanelAfterRender: function(component, eOpts) {
    var AccessEdit=Portal.util.Util.appAccessEdit(this.getView().xtype),
      r=this.getReferences();
    console.log(AccessEdit);
    r.btLoadFile.setHidden(!AccessEdit);
    Ext.getStore('Deads.main').load();
  }

});
