/*
 * File: app/view/LoadUpr/AddPeriod.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.AddPeriod', {
  extend: 'Ext.window.Window',
  alias: 'widget.loadupr.addperiod',

  requires: [
    'Portal.view.LoadUpr.AddPeriodViewModel',
    'Portal.view.LoadUpr.AddPeriodViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.field.Number',
    'Ext.form.field.ComboBox'
  ],

  controller: 'loadupr.addperiod',
  viewModel: {
    type: 'loadupr.addperiod'
  },
  modal: true,
  height: 191,
  width: 400,
  layout: 'fit',
  title: 'Новый период',
  defaultListenerScope: true,

  items: [
    {
      xtype: 'form',
      reference: 'form',
      bodyPadding: 10,
      url: 'data/LoadUpr/newPeriod.php',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'container',
              padding: 10,
              items: [
                {
                  xtype: 'button',
                  formBind: true,
                  reference: 'btSave',
                  iconCls: 'dialog-save',
                  text: 'Сохранить',
                  listeners: {
                    click: {
                      fn: 'onSaveClick',
                      scope: 'controller'
                    }
                  }
                },
                {
                  xtype: 'button',
                  iconCls: 'dialog-cancel',
                  text: 'Отмена',
                  listeners: {
                    click: 'onCancelClick'
                  }
                }
              ]
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'numberfield',
          anchor: '100%',
          reference: 'years',
          fieldLabel: 'Год',
          name: 'years',
          allowBlank: false,
          maxValue: 2030,
          minValue: 2017,
          listeners: {
            change: {
              fn: 'onYearChange',
              scope: 'controller'
            }
          }
        },
        {
          xtype: 'combobox',
          anchor: '100%',
          reference: 'months',
          fieldLabel: 'Месяц',
          name: 'months',
          allowBlank: false,
          allQuery: '0',
          displayField: 'name',
          queryParam: 'mode',
          store: 'LoadUpr.Months',
          valueField: 'id'
        },
        {
          xtype: 'numberfield',
          anchor: '100%',
          fieldLabel: 'Количество рабочих дней',
          labelWidth: 200,
          name: 'worksday',
          allowBlank: false,
          maxValue: 31,
          minValue: 1
        }
      ]
    }
  ],
  listeners: {
    afterrender: {
      fn: 'onWindowAfterRender',
      scope: 'controller'
    }
  },

  onCancelClick: function(button, e, eOpts) {
    this.close();
  }

});