/*
 * File: app/view/LoadUpr/InputTimes.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.InputTimes', {
  extend: 'Ext.window.Window',
  alias: 'widget.loadupr.inputtimes',

  requires: [
    'Portal.view.LoadUpr.InputTimesViewModel',
    'Portal.view.LoadUpr.InputTimesViewController',
    'Ext.toolbar.Toolbar',
    'Ext.form.field.ComboBox',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.grid.column.Number',
    'Ext.form.field.Number',
    'Ext.view.Table',
    'Ext.grid.plugin.CellEditing'
  ],

  controller: 'loadupr.inputtimes',
  viewModel: {
    type: 'loadupr.inputtimes'
  },
  modal: true,
  height: 387,
  width: 635,
  layout: 'fit',
  title: 'Временной показатель',
  maximizable: true,
  defaultListenerScope: true,

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'combobox',
          reference: 'cbYear',
          editable: false,
          emptyText: 'Год',
          allQuery: '0',
          autoLoadOnValue: true,
          displayField: 'years',
          store: 'LoadUpr.Years',
          valueField: 'years',
          listeners: {
            change: {
              fn: 'onYearChange',
              scope: 'controller'
            }
          }
        },
        {
          xtype: 'combobox',
          reference: 'cbMonth',
          disabled: true,
          editable: false,
          emptyText: 'Месяц',
          allQuery: '0',
          displayField: 'name',
          queryParam: 'mode',
          store: 'LoadUpr.Months',
          valueField: 'id',
          listeners: {
            change: {
              fn: 'onMonthChange',
              scope: 'controller'
            }
          }
        },
        {
          xtype: 'button',
          iconCls: 'icon-add',
          text: 'Добавить новый период',
          listeners: {
            click: 'onAddPeriodClick'
          }
        },
        {
          xtype: 'button',
          reference: 'PeriodClose',
          disabled: true,
          iconCls: 'icon-dead',
          text: 'Закрыть период',
          listeners: {
            click: {
              fn: 'onPeriodCloseClick',
              scope: 'controller'
            }
          }
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      reference: 'tbTime',
      store: 'LoadUpr.Times',
      columns: [
        {
          xtype: 'rownumberer',
          width: 34
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          width: 176,
          dataIndex: 'name_full',
          text: 'Показатель'
        },
        {
          xtype: 'numbercolumn',
          width: 121,
          align: 'end',
          dataIndex: 'var_data',
          text: 'Значение, минуты',
          editor: {
            xtype: 'numberfield',
            minValue: 0,
            step: 0.5
          }
        }
      ],
      plugins: [
        {
          ptype: 'cellediting',
          listeners: {
            edit: 'onCellEditingEdit'
          }
        }
      ]
    }
  ],
  listeners: {
    afterrender: {
      fn: 'onWindowAfterRender',
      scope: 'controller'
    }
  },

  onAddPeriodClick: function(button, e, eOpts) {
    Ext.create('Portal.view.LoadUpr.AddPeriod').show();
  },

  onCellEditingEdit: function(editor, context, eOpts) {
    var //d=this.getReferences().dateParams.getValue(),
    s=Ext.getStore('LoadUpr.Times');
            console.log(context.record.data);
    Ext.Ajax.request({
      url: 'data/LoadUpr/Times-edit.php',
      params: {
        action:"edit",
        id:context.record.data.id,
        var_data:context.record.data.var_data
      },
      success: function(r) {
        s.reload();
      }
    });
  }

});