/*
 * File: app/view/switchUsers/edit.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.switchUsers.edit', {
  extend: 'Ext.window.Window',
  alias: 'widget.switchusers.edit',

  requires: [
    'Portal.view.switchUsers.editViewModel',
    'Portal.view.switchUsers.editViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.FieldSet',
    'Ext.form.FieldContainer',
    'Ext.form.field.Hidden',
    'Ext.form.field.ComboBox',
    'Ext.form.field.Checkbox',
    'Ext.form.field.Date'
  ],

  controller: 'switchusers.edit',
  viewModel: {
    type: 'switchusers.edit'
  },
  modal: true,
  height: 309,
  width: 542,
  layout: 'fit',
  title: 'Данные о пользователе',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      bodyPadding: 10,
      url: 'data/switchUsers/save.php',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'container',
              padding: 10,
              items: [
                {
                  xtype: 'button',
                  iconCls: 'dialog-save',
                  text: 'Сохранить',
                  listeners: {
                    click: 'onSaveClick'
                  }
                },
                {
                  xtype: 'button',
                  iconCls: 'dialog-cancel',
                  text: 'Отмена',
                  listeners: {
                    click: 'onCancelClick'
                  }
                }
              ]
            },
            {
              xtype: 'container',
              flex: 1,
              layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'end'
              },
              items: [
                {
                  xtype: 'button',
                  text: 'Данные учетной записи АИС ЕГРП'
                }
              ]
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'fieldset',
          title: 'Ф.И.О.',
          items: [
            {
              xtype: 'fieldcontainer',
              layout: 'column',
              items: [
                {
                  xtype: 'textfield',
                  width: 227,
                  fieldLabel: 'Ф.',
                  labelWidth: 20,
                  name: 'userFm'
                },
                {
                  xtype: 'textfield',
                  padding: '0 0 0 10',
                  width: 220,
                  fieldLabel: 'И.',
                  labelWidth: 20,
                  name: 'userIm'
                }
              ]
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'О.',
              labelWidth: 20,
              name: 'userOt'
            }
          ]
        },
        {
          xtype: 'hiddenfield',
          anchor: '100%',
          fieldLabel: 'Label',
          name: 'id',
          listeners: {
            change: 'onIDChange'
          }
        },
        {
          xtype: 'fieldset',
          title: 'Отдел',
          items: [
            {
              xtype: 'combobox',
              anchor: '100%',
              name: 'otdel_id',
              autoLoadOnValue: true,
              displayField: 'name',
              valueField: 'id',
              bind: {
                store: '{otdels}'
              }
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Планировщик',
          items: [
            {
              xtype: 'checkboxfield',
              anchor: '100%',
              fieldLabel: 'В данный момент "Выключен"',
              labelWidth: 200,
              name: 'off'
            },
            {
              xtype: 'fieldcontainer',
              layout: 'column',
              items: [
                {
                  xtype: 'datefield',
                  fieldLabel: 'Выключить с',
                  labelWidth: 80,
                  name: 'dateOff',
                  format: 'Y-m-d'
                },
                {
                  xtype: 'datefield',
                  padding: '0 0 0 10',
                  fieldLabel: 'Включить с',
                  labelWidth: 80,
                  name: 'dateOn',
                  format: 'Y-m-d'
                }
              ]
            }
          ]
        }
      ]
    }
  ]

});