/*
 * File: app/view/switchUsers/editViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.switchUsers.editViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.switchusers.edit',

  onSaveClick: function(button, e, eOpts) {
    var me=this;
    me.getReferences().form.getForm().submit({
      success:function(f,a) {
        Ext.getStore('switchUsers.users').reload();
        me.getView().close();
      },
      failure:function(f,a) {
        Ext.Msg.alert('Failed',a.result.msg);
      }
    });
  },

  onCancelClick: function(button, e, eOpts) {
    this.getView().close();
  },

  onDelUserClick: function(button, e, eOpts) {
    var me=this,id=me.getReferences().form.getValues().id;
    Ext.Msg.show({
      title:'Внимание!',
      message:'Вы действительно желаете удалить данного пользователя?<br>Удаление производится <u>на Портале, в Домене и в базе ЕГРП</u>?!<br><font color="red"><b>Восстановление будет невозможно!</b></font>',
      buttons:Ext.Msg.YESNO,
      icon:Ext.Msg.QUESTION,
      fn:function(b){
        if(b==='yes'){
          Ext.Msg.show({
            title:'Внимание!',
            message:'<font color="red"><b>Последний раз спрашиваю: Абсолютно уверен, что надо удалить этого пользователя?<br><u>Восстановление будет невозможно!</u></b></font>',
            buttons:Ext.Msg.YESNO,
            icon:Ext.Msg.QUESTION,
            fn:function(btn){
              if(btn==='yes'){
                var Mask=new Ext.LoadMask({msg:'Работаю...'}).show();
                Ext.Ajax.request({
                  url:'data/switchUsers/userDel.php',
                  params:{id:id},
                  success: function(r,o) {
                    Mask.destroy();
                    var m=Portal.util.Util.decodeJSON(r.responseText).msg;
                    Ext.Msg.alert('Результат операции',m);
                    Ext.getStore('switchUsers.users').reload();
                    //console.log(me.getView());
                    me.getView().close();
                  },
                  failure: function(r,o) {
                    Mask.destroy();
                    Ext.Msg.alert('Результат операции','server-side failure with status code '+r.status);
                  }
                });
              }},scope:me});
            }},scope:me});
  },

  onIDChange: function(field, newValue, oldValue, eOpts) {
    /*var p=this.getReferences().form.getForm().getValues();
    console.log(p);
    Ext.Ajax.request({
    url:'data/switchUsers/getEGRPdata.php',
    params:{id:newValue},
    method:"GET",
    success: function(r,o) {
    var obj = Ext.decode(r.responseText);
    console.dir(obj);
    },
    failure: function(r,o) {
    console.log('server-side failure with status code ' + r.status);
    }
    });*/
  }

});
