/*
 * File: app/view/switchUsers/mainViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.switchUsers.mainViewModel', {
  extend: 'Ext.app.ViewModel',
  alias: 'viewmodel.switchusers.main',

  requires: [
    'Ext.data.Store',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.field.Date',
    'Ext.data.field.Boolean'
  ],

  stores: {
    users: {
      proxy: {
        type: 'ajax',
        url: 'data/switchUsers/data.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'username'
        },
        {
          name: 'main_group'
        },
        {
          name: 'userFm'
        },
        {
          name: 'userIm'
        },
        {
          name: 'userOt'
        },
        {
          name: 'otdel_id'
        },
        {
          type: 'date',
          name: 'dateOff'
        },
        {
          type: 'date',
          name: 'dateOn'
        },
        {
          name: 'ad_state'
        },
        {
          type: 'boolean',
          name: 'off'
        }
      ]
    }
  }

});