/*
 * File: app/view/certManager/mainViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.certManager.mainViewModel', {
	extend: 'Ext.app.ViewModel',
	alias: 'viewmodel.certmanager.main',

	requires: [
		'Ext.data.Store',
		'Ext.data.proxy.Ajax',
		'Ext.data.reader.Json',
		'Ext.data.field.Field'
	],

	stores: {
		main: {
			proxy: {
				type: 'ajax',
				url: 'data/certManager/data.php',
				reader: {
					type: 'json',
					rootProperty: 'data'
				}
			},
			fields: [
				{
					name: 'id'
				},
				{
					name: 'is_root'
				},
				{
					name: 'sn'
				},
				{
					name: 'validFrom'
				},
				{
					name: 'validTo'
				},
				{
					name: 'subj_O'
				},
				{
					name: 'subj_CN'
				},
				{
					name: 'subj_Title'
				},
				{
					name: 'subj_Email'
				},
				{
					name: 'uc_CN'
				},
				{
					name: 'uc_Email'
				},
				{
					name: 'uc_O'
				},
				{
					name: 'uc_Address'
				},
				{
					name: 'uc_OU'
				},
				{
					name: 'filepath'
				},
				{
					name: 'subj_SNG'
				}
			]
		}
	}

});