/*
 * File: app/view/certManager/mainViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.certManager.mainViewController', {
	extend: 'Ext.app.ViewController',
	alias: 'controller.certmanager.main',

	onRefreshClick: function(button, e, eOpts) {
		this.getStore('main').reload();
	},

	onRescanClick: function(button, e, eOpts) {
		var me=this;
		Ext.Ajax.request({
			url: 'data/certManager/crt2.php',
			success: function(response){
				me.getStore('main').load();
			}
		});
		//me.getStore('main').load();
	},

	onGridpanelSelectionChange: function(model, selected, eOpts) {
		console.log(selected[0].data);
		this.getReferences().form.update(selected[0].data);
	},

	onMainActivate: function(component, eOpts) {
		this.getStore('main').load();
	}

});
