/*
 * File: app/view/GKUstop/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.GKUstop.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.gkustop',

  requires: [
    'Portal.view.GKUstop.mainViewModel',
    'Portal.view.GKUstop.mainViewController',
    'Ext.container.ButtonGroup',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.view.Table',
    'Ext.grid.filters.filter.String',
    'Ext.grid.column.Date',
    'Ext.grid.filters.filter.Date',
    'Ext.grid.filters.filter.List',
    'Ext.grid.filters.Filters',
    'Ext.toolbar.Paging',
    'Ext.form.Panel',
    'Ext.XTemplate',
    'Ext.form.FieldContainer',
    'Ext.form.field.Date'
  ],

  controller: 'gkustop.main',
  viewModel: {
    type: 'gkustop.main'
  },
  height: 469,
  width: 1257,
  layout: 'border',
  title: 'My Panel',

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'buttongroup',
          reference: 'blFKP',
          title: 'ФКП',
          columns: 2,
          items: [
            {
              xtype: 'button',
              reference: 'btKPadd',
              iconCls: 'icon-add',
              text: 'Добавить запись',
              listeners: {
                click: 'onKPadd'
              }
            },
            {
              xtype: 'button',
              reference: 'btKPedit',
              disabled: true,
              iconCls: 'icon-edit',
              text: 'Изменить запись',
              listeners: {
                click: 'onKPedit'
              }
            }
          ]
        },
        {
          xtype: 'buttongroup',
          reference: 'blRR',
          title: 'Росреестр',
          columns: 2,
          items: [
            {
              xtype: 'button',
              reference: 'btRRedit',
              disabled: true,
              iconCls: 'icon-edit',
              text: 'Дополнить запись',
              listeners: {
                click: 'onRRedit'
              }
            }
          ]
        },
        {
          xtype: 'buttongroup',
          title: 'Инструменты',
          columns: 4,
          items: [
            {
              xtype: 'button',
              iconCls: 'icon-mime-excel',
              listeners: {
                click: 'onExcel'
              }
            },
            {
              xtype: 'button',
              iconCls: 'icon-refresh',
              text: 'Обновить',
              listeners: {
                click: 'onRefresh'
              }
            },
            {
              xtype: 'button',
              iconCls: 'filter-minus',
              text: 'Сбросить фильтр',
              listeners: {
                click: 'onFilterReset'
              }
            },
            {
              xtype: 'button',
              text: 'Список кадастровых инженеров',
              listeners: {
                click: 'onEngineers'
              }
            }
          ]
        }
      ]
    },
    {
      xtype: 'toolbar',
      dock: 'top',
      hidden: true,
      items: [
        {
          xtype: 'textfield',
          width: 197,
          emptyText: 'Номер заявления'
        },
        {
          xtype: 'fieldcontainer',
          layout: 'column',
          fieldLabel: 'Дата подачи',
          items: [
            {
              xtype: 'datefield',
              width: 120,
              fieldLabel: 'С',
              labelWidth: 15
            },
            {
              xtype: 'datefield',
              width: 128,
              fieldLabel: 'По',
              labelWidth: 20
            }
          ]
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      region: 'center',
      reference: 'grid',
      store: 'GKUstop.main',
      columns: [
        {
          xtype: 'rownumberer'
        },
        {
          xtype: 'gridcolumn',
          baseCls: 'x-component x-panel-style2',
          text: 'ФКП',
          columns: [
            {
              xtype: 'gridcolumn',
              width: 160,
              dataIndex: 'zayav',
              text: '№ Заявления',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'datecolumn',
              width: 75,
              dataIndex: 'zayav_date',
              text: 'Дата<br>подачи',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'ONvid_N',
              text: 'Вид ОН',
              filter: {
                type: 'list'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'zayav_type_N',
              text: 'Тип заявления',
              filter: {
                type: 'list'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'charc',
              text: 'Характеристика'
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'KU_date_uchet',
              text: 'Учет',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'KU_date_stop',
              text: 'Приостановление',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'KU_date_none',
              text: 'Отказ',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'KU_FZ',
              text: '218-ФЗ'
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'KU_treb',
              text: 'Требования'
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'CadEngineer_N',
              text: 'Инженер',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'KU_user_fio',
              text: 'Ф.И.О. спец.',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'KU_refer',
              text: 'Примечание'
            }
          ]
        },
        {
          xtype: 'gridcolumn',
          baseCls: 'x-component x-panel-style3',
          text: 'Росреестр',
          columns: [
            {
              xtype: 'gridcolumn',
              dataIndex: 'RR_user_fio',
              text: 'Ф.И.О. спец.',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'RR_date_uchet',
              text: 'Учет',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'RR_date_stop',
              text: 'Приостановление',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'datecolumn',
              width: 70,
              dataIndex: 'RR_date_none',
              text: 'Отказ',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'RR_FZ',
              text: '218-ФЗ'
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'RR_treb',
              text: 'Требования'
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'RR_refer',
              text: 'Примечания'
            }
          ]
        }
      ],
      viewConfig: {
        getRowClass: function(record, rowIndex, rowParams, store) {
          if(record.data.RR_user_id>0){return "x-panel-style3";}
        }
      },
      listeners: {
        selectionchange: 'onGridSelectionChange',
        filterchange: 'onFilterChange'
      },
      plugins: [
        {
          ptype: 'gridfilters',
          id: 'GKUfilter',
          menuFilterText: 'Фильтр'
        }
      ],
      dockedItems: [
        {
          xtype: 'pagingtoolbar',
          dock: 'bottom',
          afterPageText: 'из {0}',
          beforePageText: 'Страница',
          displayInfo: true,
          displayMsg: 'Показано {0} - {1} из {2}',
          emptyMsg: 'Нет данных для показа',
          firstText: 'Первая страница',
          lastText: 'Последняя страница',
          nextText: 'Следующая страница',
          prevText: 'Предыдущая страница',
          refreshText: 'Обновить',
          store: 'GKUstop.main'
        }
      ]
    },
    {
      xtype: 'form',
      region: 'south',
      reference: 'info',
      height: 81,
      hidden: true,
      padding: 7,
      tpl: [
        '{zayav}'
      ]
    }
  ],
  listeners: {
    afterrender: 'onAfterRender'
  }

});