/*
 * File: app/model/LoadUpr/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.model.LoadUpr.main', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.field.Field'
  ],

  fields: [
    {
      name: 'id'
    },
    {
      name: 'name_full'
    },
    {
      name: 'time_fact'
    },
    {
      name: 'beginDocs2regs'
    },
    {
      name: 'KU_regs'
    },
    {
      name: 'KU_MakeDocs'
    },
    {
      name: 'RPKU_regs'
    },
    {
      name: 'RPKU_MakeDocs'
    },
    {
      name: 'RP_regs'
    },
    {
      name: 'RP_MakeDocs'
    },
    {
      name: 'EP_regs'
    },
    {
      name: 'EP_MakeDocs'
    },
    {
      name: 'Arest'
    },
    {
      name: 'InsertOldObj'
    },
    {
      name: 'IsprErrorGKN'
    },
    {
      name: 'MVedGKN'
    },
    {
      name: 'GRP_MakeCopyRightDocs'
    },
    {
      name: 'GRP_StatKUVI'
    },
    {
      name: 'GRP_StatPORTAL'
    },
    {
      name: 'GZN_Proverok'
    },
    {
      name: 'GFD_Human'
    },
    {
      name: 'GFD_Lists'
    },
    {
      name: 'DPD'
    },
    {
      name: 'DP_InputDocs'
    },
    {
      name: 'DP_OutHuman'
    },
    {
      name: 'DP_OutOther'
    },
    {
      name: 'WorksHourInDay'
    },
    {
      name: 'SotrudnikHour'
    },
    {
      name: 'SotrudnikDay'
    },
    {
      name: 'LoadSotrudnikDay'
    }
  ]
});