/*
 * File: app/view/ETables/main.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.etablesmain',

  requires: [
    'Portal.view.ETables.mainViewModel',
    'Portal.view.ETables.mainViewController',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.view.Table',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.selection.RowModel',
    'Ext.grid.plugin.RowEditing'
  ],

  controller: 'etables.main',
  viewModel: {
    type: 'etables.main'
  },
  height: 398,
  width: 588,
  layout: 'border',
  title: 'My Panel',
  defaultListenerScope: true,

  items: [
    {
      xtype: 'gridpanel',
      region: 'west',
      split: true,
      reference: 'tblMain',
      width: 230,
      collapsible: true,
      title: 'Таблицы',
      store: 'ETables.tables',
      columns: [
        {
          xtype: 'rownumberer',
          dataIndex: 'string'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          dataIndex: 'title',
          text: 'Наименование'
        }
      ],
      viewConfig: {
        listeners: {
          selectionchange: {
            fn: 'onTableSelectionChange',
            scope: 'controller'
          },
          itemdblclick: {
            fn: 'onTableItemDblClick',
            scope: 'controller'
          }
        }
      },
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'btnAdd',
              iconCls: 'icon-add',
              listeners: {
                click: {
                  fn: 'onTAddClick',
                  scope: 'controller'
                }
              }
            },
            {
              xtype: 'button',
              reference: 'btnDelete',
              disabled: true,
              iconCls: 'icon-delete'
            },
            {
              xtype: 'button',
              reference: 'btnRefresh',
              iconCls: 'icon-refresh',
              listeners: {
                click: {
                  fn: 'onRefreshClick',
                  scope: 'controller'
                }
              }
            },
            {
              xtype: 'button',
              reference: 'btnTEdit',
              disabled: true,
              iconCls: 'icon-edit',
              listeners: {
                click: {
                  fn: 'onEditClick',
                  scope: 'controller'
                }
              }
            },
            {
              xtype: 'button',
              reference: 'btnTblEdit',
              disabled: true,
              text: 'MyButton',
              listeners: {
                click: {
                  fn: 'onEditDBClick',
                  scope: 'controller'
                }
              }
            }
          ]
        }
      ],
      selModel: {
        selType: 'rowmodel'
      }
    },
    {
      xtype: 'gridpanel',
      region: 'center',
      reference: 'MainPanel',
      title: '*',
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'string',
          text: 'String'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'tbAdd',
              iconCls: 'icon-add',
              listeners: {
                click: {
                  fn: 'onTbAddClick',
                  scope: 'controller'
                }
              }
            },
            {
              xtype: 'button',
              reference: 'tbDel',
              iconCls: 'icon-delete',
              listeners: {
                click: {
                  fn: 'onTbDelClick',
                  scope: 'controller'
                }
              }
            },
            {
              xtype: 'button',
              reference: 'tbRefresh',
              iconCls: 'icon-refresh',
              listeners: {
                click: {
                  fn: 'onTbRefreshClick',
                  scope: 'controller'
                }
              }
            }
          ]
        }
      ],
      plugins: [
        {
          ptype: 'rowediting',
          listeners: {
            edit: 'onRowEditingEdit'
          }
        }
      ]
    },
    {
      xtype: 'panel',
      region: 'south',
      reference: 'pInfo',
      height: 61,
      scrollable: true
    }
  ],
  listeners: {
    afterrender: {
      fn: 'onPanelAfterRender',
      scope: 'controller'
    }
  },

  onRowEditingEdit: function(editor, context, eOpts) {
    var r=this.getReferences(),
        st=Ext.getStore('ETables.main'),
        stR=r.MainPanel.getSelection()[0].data.id;
    context.newValues._t=stR;
    Ext.Ajax.request({
        url:'data/ETables/table-upd.php',
        params:context.newValues,
        success:function(r){st.reload();}
    });
    //r.btnDelRecRef.setDisabled(true);
    //r.btnAddRecRef.setDisabled(false);
    //r.btnRefreshRef.setDisabled(false);
  }

});