/*
 * File: app/view/ETables/main.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.etablesmain',

  requires: [
    'Portal.view.ETables.mainViewModel',
    'Portal.view.ETables.mainViewController',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.view.Table',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.selection.RowModel',
    'Ext.grid.column.Number',
    'Ext.grid.column.Date',
    'Ext.grid.column.Boolean',
    'Ext.grid.plugin.CellEditing'
  ],

  controller: 'etables.main',
  viewModel: {
    type: 'etables.main'
  },
  height: 398,
  width: 588,
  layout: 'border',
  title: 'My Panel',

  items: [
    {
      xtype: 'gridpanel',
      region: 'west',
      split: true,
      reference: 'tblMain',
      width: 230,
      closable: true,
      title: 'Таблицы',
      store: 'ETables.tables',
      columns: [
        {
          xtype: 'rownumberer',
          dataIndex: 'string'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          dataIndex: 'title',
          text: 'Наименование'
        }
      ],
      viewConfig: {
        listeners: {
          selectionchange: 'onTableSelectionChange',
          itemdblclick: 'onTableItemDblClick'
        }
      },
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'btnAdd',
              iconCls: 'icon-add',
              listeners: {
                click: 'onTAddClick'
              }
            },
            {
              xtype: 'button',
              reference: 'btnDelete',
              disabled: true,
              iconCls: 'icon-delete'
            },
            {
              xtype: 'button',
              reference: 'btnRefresh',
              iconCls: 'icon-refresh',
              listeners: {
                click: 'onRefreshClick'
              }
            },
            {
              xtype: 'button',
              reference: 'btnTEdit',
              disabled: true,
              iconCls: 'icon-edit',
              listeners: {
                click: 'onEditClick'
              }
            },
            {
              xtype: 'button',
              reference: 'btnTblEdit',
              disabled: true,
              text: 'MyButton',
              listeners: {
                click: 'onEditDBClick'
              }
            }
          ]
        }
      ],
      selModel: {
        selType: 'rowmodel'
      }
    },
    {
      xtype: 'gridpanel',
      region: 'center',
      reference: 'MainPanel',
      title: '*',
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'string',
          text: 'String'
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'number',
          text: 'Number'
        },
        {
          xtype: 'datecolumn',
          dataIndex: 'date',
          text: 'Date'
        },
        {
          xtype: 'booleancolumn',
          dataIndex: 'bool',
          text: 'Boolean'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'tbAdd',
              iconCls: 'icon-add',
              listeners: {
                click: 'onTbAddClick'
              }
            },
            {
              xtype: 'button',
              reference: 'tbDel',
              iconCls: 'icon-delete',
              listeners: {
                click: 'onTbDelClick'
              }
            },
            {
              xtype: 'button',
              reference: 'tbRefresh',
              iconCls: 'icon-refresh',
              listeners: {
                click: 'onTbRefreshClick'
              }
            }
          ]
        }
      ],
      plugins: [
        {
          ptype: 'cellediting'
        }
      ]
    },
    {
      xtype: 'panel',
      region: 'south',
      reference: 'pInfo',
      height: 61,
      scrollable: true
    }
  ],
  listeners: {
    afterrender: 'onPanelAfterRender'
  }

});