/*
 * File: app/view/ETables/mainViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.mainViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.etables.main',

  onTableSelectionChange: function(model, selected, eOpts) {
    var r=this.getReferences(),db=selected[0].data,mp=r.MainPanel;
    r.pInfo.setHtml(db.info);
    //console.log(selected);
    r.btnTblEdit.setDisabled(false);
    r.btnTEdit.setDisabled(false);
    r.btnDelete.setDisabled(false);
  },

  onTableItemDblClick: function(dataview, record, item, index, e, eOpts) {
    var r=this.getReferences(),db=record.data,mp=r.MainPanel,
      newcolumns=[{xtype:'rownumberer'}],
      MainStore = Ext.getStore('ETables.main'),
      FieldStore = this.getStore('tbFields');

    console.log(db.title);
    mp.setTitle(db.title);

    FieldStore.load({params:{main_id:db.id},scope:this,
    callback:function(records,o,success){
      //console.log(records);
      FieldStore.each(function(rec){
        //console.log(rec);
        var tempvar={},r=rec.data;
        console.log(r.field_name);
        if(r.field_name != 'id'){
          tempvar={
            dataIndex:r.field_name,
            tooltip: r.field_name,
            header: r.field_title,
            name: r.field_name,
            xtype:record.get('xtype') //'checkcolumn'
            //            width:100
          };
          newcolumns.push(tempvar);
        }
      });

      mp.reconfigure(MainStore, newcolumns);
    }});
    MainStore.load({params:{id:db.id}});
  },

  onTAddClick: function(button, e, eOpts) {
    var w=Ext.create('Portal.view.ETables.TblNew').show();
    w.down("form").getForm().setValues({id:0});
  },

  onRefreshClick: function(button, e, eOpts) {
    Ext.getStore('ETables.tables').reload();
  },

  onEditClick: function(button, e, eOpts) {
    var w=Ext.create('Portal.view.ETables.TblNew');
    w.down("form").getForm().setValues(this.getReferences().tblMain.getSelection()[0].data);
    w.show();
  },

  onEditDBClick: function(button, e, eOpts) {
    var d=this.getReferences().tblMain.getSelection()[0].data,
      w=Ext.create('Portal.view.ETables.TblEdit',{itemId:d.id});
    w.setTitle(d.title);
    w.show();
  },

  onTbAddClick: function(button, e, eOpts) {
    //console.log(this.getView().getItemId());
    var view=this.getView(),
      rec = new Portal.model.ETables.TblFileds({
        a_id:view.getItemId(),
        field_title:'',
        field_type:'VARCHAR',
        field_len:20,
        field_order:0,
        id:0
      });

    this.getStore('fields').insert(0, rec);
    this.getReferences().table.findPlugin('rowediting').startEdit(rec, 0);
  },

  onTbDelClick: function(button, e, eOpts) {

  },

  onTbRefreshClick: function(button, e, eOpts) {
    Ext.getStore('ETables.main').reload();
  },

  onPanelAfterRender: function(component, eOpts) {
    Ext.getStore('ETables.tables').load();
  }

});
