/*
 * File: app/view/ETables/TblEdit.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.TblEdit', {
  extend: 'Ext.window.Window',
  alias: 'widget.etables.tbledit',

  requires: [
    'Portal.view.ETables.TblEditViewModel',
    'Portal.view.ETables.TblEditViewController',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.form.field.ComboBox',
    'Ext.grid.column.Number',
    'Ext.form.field.Number',
    'Ext.grid.column.Check',
    'Ext.form.field.Checkbox',
    'Ext.grid.column.Action',
    'Ext.view.Table',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.grid.plugin.RowEditing'
  ],

  controller: 'etables.tbledit',
  viewModel: {
    type: 'etables.tbledit'
  },
  modal: true,
  height: 422,
  minWidth: 1,
  width: 715,
  layout: 'border',
  title: 'My Window',

  items: [
    {
      xtype: 'gridpanel',
      region: 'center',
      reference: 'table',
      disabled: true,
      bind: {
        store: '{fields}'
      },
      columns: [
        {
          xtype: 'rownumberer'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          width: 143,
          dataIndex: 'field_title',
          text: 'Имя столбца (поля)',
          editor: {
            xtype: 'textfield',
            allowBlank: false
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'field_type',
          text: 'Тип',
          editor: {
            xtype: 'combobox',
            autoLoadOnValue: true,
            displayField: 'name',
            valueField: 'id',
            bind: {
              store: '{f_type}'
            }
          }
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'field_len',
          reference: 'field_len',
          text: 'Размер типа (длина)',
          format: '0',
          editor: {
            xtype: 'numberfield'
          }
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'width',
          text: 'Ширина столбца',
          format: '0',
          editor: {
            xtype: 'numberfield'
          }
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'field_order',
          text: 'Порядок',
          format: '0',
          editor: {
            xtype: 'numberfield'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'editor',
          text: 'Редактор',
          editor: {
            xtype: 'combobox',
            displayField: 'name',
            valueField: 'id',
            bind: {
              store: '{e_type}'
            }
          }
        },
        {
          xtype: 'checkcolumn',
          dataIndex: 'allowBlank',
          text: 'Обязательное',
          editor: {
            xtype: 'checkboxfield'
          }
        },
        {
          xtype: 'actioncolumn',
          items: [
            {

            }
          ]
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'btnAdd',
              iconCls: 'icon-add',
              listeners: {
                click: 'onAddClick'
              }
            },
            {
              xtype: 'button',
              reference: 'btnDel',
              disabled: true,
              iconCls: 'icon-delete',
              listeners: {
                click: 'onDelClick'
              }
            },
            {
              xtype: 'button',
              iconCls: 'icon-refresh',
              text: 'Обновить',
              listeners: {
                click: 'onRefreshClick'
              }
            }
          ]
        }
      ],
      plugins: [
        {
          ptype: 'rowediting',
          autoUpdate: true
        }
      ],
      listeners: {
        selectionchange: 'onGridSelectionChange'
      }
    },
    {
      xtype: 'panel',
      region: 'south',
      height: 74,
      padding: 5,
      items: [
        {
          xtype: 'container',
          html: '<center><font color=\'red\'><b>Внимание!</b><br>Редактирование данного раздела может удалить ваши данные!</font></center>',
          padding: 5
        },
        {
          xtype: 'container',
          layout: 'fit',
          items: [
            {
              xtype: 'button',
              text: 'Понимаю риск. Хочу разблокировать и редактировать',
              listeners: {
                click: 'onRiskClick'
              }
            }
          ]
        }
      ]
    }
  ],
  listeners: {
    afterrender: 'onWindowAfterRender'
  }

});