/*
 * File: app/view/ETables/TblEditViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.TblEditViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.etables.tbledit',

  onAddClick: function(button, e, eOpts) {
    console.log('Таблица в записи = ' + this.getView().getMinWidth());

    var rec = new Portal.model.ETables.TblFileds({
      a_id:this.getView().getMinWidth(),
      field_title:'',
      field_type:'VARCHAR',
      field_len:20,
      field_order:0,
      id:0
    });

    this.getStore('fields').insert(0, rec);
    this.getReferences().table.findPlugin('rowediting').startEdit(rec, 0);
  },

  onDelClick: function(button, e, eOpts) {

  },

  onRefreshClick: function(button, e, eOpts) {
    this.getStore('fields').reload(this.getView().getMinWidth());
  },

  onGridSelectionChange: function(model, selected, eOpts) {
    this.getReferences().btnDel.setDisabled(false);
  },

  onWindowAfterRender: function(component, eOpts) {
    var m=this,id=m.getView().getMinWidth();
    m.getStore('fields').load(
    {params:{main_id:id}});
  },

  onRiskClick: function(button, e, eOpts) {
    this.getReferences().table.setDisabled(false);
  }

});
