/*
 * File: app/view/ETables/TblNew.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ETables.TblNew', {
  extend: 'Ext.window.Window',
  alias: 'widget.etables.tblnew',

  requires: [
    'Portal.view.ETables.TblNewViewModel',
    'Portal.view.ETables.TblNewViewController',
    'Ext.form.Panel',
    'Ext.form.field.TextArea',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.field.Hidden'
  ],

  controller: 'etables.tblnew',
  viewModel: {
    type: 'etables.tblnew'
  },
  modal: true,
  height: 231,
  width: 531,
  layout: 'fit',
  title: 'Новая таблица',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      bodyPadding: 10,
      items: [
        {
          xtype: 'textfield',
          anchor: '100%',
          name: 'title',
          allowBlank: false,
          emptyText: 'Наименование таблицы',
          maxLength: 50,
          listeners: {
            change: 'onTitleChange'
          }
        },
        {
          xtype: 'textareafield',
          anchor: '100%',
          height: 103,
          fieldLabel: 'Описание таблицы',
          labelAlign: 'top',
          name: 'info'
        },
        {
          xtype: 'hiddenfield',
          anchor: '100%',
          fieldLabel: 'Label',
          name: 'id'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'container',
              padding: 10,
              items: [
                {
                  xtype: 'button',
                  formBind: true,
                  iconCls: 'dialog-save',
                  text: 'Сохранить',
                  listeners: {
                    click: 'onSaveClick'
                  }
                },
                {
                  xtype: 'button',
                  iconCls: 'dialog-cancel',
                  text: 'Отмена',
                  listeners: {
                    click: 'onCancelClick'
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]

});