/*
 * File: app/view/GKUstop/RRedit.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.GKUstop.RRedit', {
  extend: 'Ext.window.Window',
  alias: 'widget.gkustop.rredit',

  requires: [
    'Portal.view.GKUstop.KPeditViewModel2',
    'Portal.view.GKUstop.KPeditViewController2',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.field.Date',
    'Ext.form.field.Hidden',
    'Ext.form.field.TextArea'
  ],

  controller: 'gkustop.rredit',
  viewModel: {
    type: 'gkustop.rredit'
  },
  modal: true,
  height: 279,
  width: 613,
  layout: 'fit',
  title: 'Новая запись',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      scrollable: true,
      bodyPadding: 10,
      url: 'data/GKUstop/RRedit.php',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              formBind: true,
              iconCls: 'dialog-save',
              text: 'Сохранить',
              listeners: {
                click: 'onSave'
              }
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'container',
          layout: 'column',
          items: [
            {
              xtype: 'datefield',
              padding: '0 5 5 0 ',
              width: 160,
              fieldLabel: 'Учет',
              labelAlign: 'top',
              labelWidth: 50,
              name: 'RR_date_uchet',
              editable: false,
              format: 'Y-m-d'
            },
            {
              xtype: 'datefield',
              padding: '0 5 0 5',
              width: 160,
              fieldLabel: 'Приостановление',
              labelAlign: 'top',
              name: 'RR_date_stop',
              editable: false,
              format: 'Y-m-d'
            },
            {
              xtype: 'datefield',
              padding: '0 0 0 5',
              width: 160,
              fieldLabel: 'Отказ',
              labelAlign: 'top',
              labelWidth: 50,
              name: 'RR_date_none',
              editable: false,
              format: 'Y-m-d'
            }
          ]
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: '218-ФЗ',
          name: 'RR_FZ'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Требования',
          name: 'RR_treb'
        },
        {
          xtype: 'hiddenfield',
          anchor: '100%',
          fieldLabel: 'Label',
          name: 'id'
        },
        {
          xtype: 'textareafield',
          anchor: '100%',
          fieldLabel: 'Примечание',
          labelAlign: 'top',
          name: 'RR_refer'
        }
      ]
    }
  ]

});