/*
 * File: app/view/Deads/File.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.Deads.File', {
  extend: 'Ext.window.Window',
  alias: 'widget.deads.file',

  requires: [
    'Portal.view.Deads.FileViewModel',
    'Portal.view.Deads.FileViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.field.File'
  ],

  controller: 'deads.file',
  viewModel: {
    type: 'deads.file'
  },
  height: 156,
  width: 449,
  layout: 'fit',
  title: 'Загрузка файла данных',

  items: [
    {
      xtype: 'form',
      reference: 'form',
      border: false,
      bodyPadding: 10,
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'container',
              padding: 10,
              items: [
                {
                  xtype: 'button',
                  formBind: true,
                  text: 'Загрузить',
                  listeners: {
                    click: 'onLoadClick'
                  }
                },
                {
                  xtype: 'button',
                  text: 'Отменить',
                  listeners: {
                    click: 'onCancelClick'
                  }
                }
              ]
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'filefield',
          anchor: '100%',
          name: 'filename',
          allowBlank: false
        }
      ]
    }
  ]

});