/*
 * File: app/view/Deads/FileViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.Deads.FileViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.deads.file',

  onLoadClick: function(button, e, eOpts) {
    var me=this,
      frm=me.lookupReference('form'),
      st=Ext.getStore('Deads.main');

    if (frm.isValid()) {

      frm.submit({
        url:'data/Deads/load.php',
        target:'_blank',
        waitMsg:'Загружаю документ...',
        success:function(fp,o) {
          re=Portal.util.Util.decodeJSON(o.response.responseText);
          //console.log(re);
          st.reload();
          me.getView().close();
        },
        failure:function(fp,o) {
          //console.log(o);
          re=Portal.util.Util.decodeJSON(o.response.responseText).msg;
          //console.log(re);
          Ext.Msg.alert('Ошибка',re);
          me.getView().close();
        }
      });
    }

  },

  onCancelClick: function(button, e, eOpts) {
    this.getView().close();
  }

});
