/*
 * File: app/view/MyWindow.js
 * Date: Fri Jan 26 2018 15:16:24 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.MyWindow', {
  extend: 'Ext.window.Window',
  alias: 'widget.mywindow',

  requires: [
    'Portal.view.MyWindowViewModel',
    'Portal.view.MyWindowViewController',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.FieldSet',
    'Ext.form.field.ComboBox',
    'Ext.form.field.Date'
  ],

  controller: 'mywindow',
  viewModel: {
    type: 'mywindow'
  },
  height: 571,
  width: 784,
  layout: 'fit',
  title: 'КН:',

  items: [
    {
      xtype: 'form',
      border: false,
      scrollable: true,
      bodyPadding: 10,
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              reference: 'Save',
              iconCls: 'dialog-save',
              text: 'Сохранить',
              listeners: {
                click: 'onSave'
              }
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'fieldset',
          title: 'Земельный участок',
          items: [
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Кадастровый номер',
              labelWidth: 120
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Адрес',
              labelWidth: 50
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Мероприятие по ГЗН',
          items: [
            {
              xtype: 'combobox',
              anchor: '100%',
              fieldLabel: 'Орган, проводивший проверку',
              labelWidth: 200
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Мероприятие'
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Форма проведения проверки',
          layout: {
            type: 'hbox',
            align: 'stretchmax',
            pack: 'center'
          },
          items: [
            {
              xtype: 'container',
              flex: 1,
              layout: 'form',
              items: [
                {
                  xtype: 'combobox',
                  flex: 1
                },
                {
                  xtype: 'combobox'
                }
              ]
            },
            {
              xtype: 'container',
              layout: 'form',
              items: [
                {
                  xtype: 'datefield',
                  fieldLabel: 'Дата начала'
                },
                {
                  xtype: 'datefield',
                  fieldLabel: 'Дата окончания'
                }
              ]
            }
          ]
        },
        {
          xtype: 'fieldset',
          layout: 'column',
          title: 'Акт проведения проверки',
          items: [
            {
              xtype: 'datefield',
              fieldLabel: 'Label'
            },
            {
              xtype: 'textfield',
              fieldLabel: 'Label'
            }
          ]
        },
        {
          xtype: 'fieldset',
          title: 'Предписание об устранении нарушений',
          items: [
            {
              xtype: 'datefield',
              anchor: '100%',
              fieldLabel: 'Label'
            },
            {
              xtype: 'textfield',
              anchor: '100%',
              fieldLabel: 'Label'
            }
          ]
        }
      ]
    }
  ]

});