/*
 * File: app/view/CadastErrors/DataInViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.CadastErrors.DataInViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.cadasterrors.datain',

  onDateInChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences();
    r.grid.setDisabled(true);
    if(r.engineer.getValue()){
      r.btnSay.setDisabled(false);
    }else{r.btnSay.setDisabled(true);}
  },

  onEngChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences();
    r.grid.setDisabled(true);
    if(r.dateIn.getValue()){
      r.btnSay.setDisabled(false);
    }else{r.btnSay.setDisabled(true);}
  },

  onSay: function(button, e, eOpts) {
    var r=this.getReferences();D=r.dateIn.getValue();Eng=r.engineer.getValue();
    this.getViewModel().getStore('datas').load({params:{eng_id:Eng,dateIn:D}});
    r.grid.setDisabled(false);
  },

  onAfterRender: function(component, eOpts) {
    this.getViewModel().getStore("engineers").load();
  }

});
