/*
 * File: app/view/CadastErrors/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.CadastErrors.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.cadasterrorsmain',

  requires: [
    'Portal.view.CadastErrors.mainViewModel',
    'Portal.view.CadastErrors.mainViewController',
    'Ext.toolbar.Toolbar',
    'Ext.container.ButtonGroup',
    'Ext.form.field.Date',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.view.Table'
  ],

  controller: 'cadasterrors.main',
  viewModel: {
    type: 'cadasterrors.main'
  },
  height: 621,
  width: 1260,
  layout: 'fit',
  title: 'My Panel',

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      layout: {
        type: 'hbox',
        align: 'stretch'
      },
      items: [
        {
          xtype: 'buttongroup',
          title: 'Период',
          items: [
            {
              xtype: 'datefield',
              reference: 'dateB',
              width: 146,
              fieldLabel: 'С',
              labelWidth: 20,
              format: 'Y-m-d',
              listeners: {
                change: 'onDBChange'
              }
            },
            {
              xtype: 'datefield',
              reference: 'dateE',
              padding: '0 0 0 10',
              width: 145,
              fieldLabel: 'По',
              labelWidth: 20,
              format: 'Y-m-d',
              listeners: {
                change: 'onDEChange'
              }
            }
          ]
        },
        {
          xtype: 'buttongroup',
          title: 'Отчет',
          items: [
            {
              xtype: 'button',
              reference: 'btnSay',
              disabled: true,
              iconCls: 'icon-say',
              text: 'Показать',
              listeners: {
                click: 'onSay'
              }
            },
            {
              xtype: 'button',
              reference: 'btnExcel',
              disabled: true,
              iconCls: 'icon-mime-excel',
              text: 'Вывести'
            }
          ]
        },
        {
          xtype: 'buttongroup',
          title: 'Настройки',
          items: [
            {
              xtype: 'button',
              flex: 1,
              iconCls: 'icon-db',
              text: 'Внести данные',
              listeners: {
                click: 'onDataInput'
              }
            },
            {
              xtype: 'button',
              text: 'Список кадастровых инженеров',
              listeners: {
                click: 'onSetEngineers'
              }
            }
          ]
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      reference: 'grid',
      columns: [
        {
          xtype: 'rownumberer'
        }
      ]
    }
  ]

});