/*
 * File: app/view/HW_PC/mainViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.HW_PC.mainViewModel', {
  extend: 'Ext.app.ViewModel',
  alias: 'viewmodel.hw_pc.main',

  requires: [
    'Ext.data.Store',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.field.Number'
  ],

  stores: {
    main: {
      proxy: {
        type: 'ajax',
        url: 'data/HW_PC/main.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'HDate'
        },
        {
          name: 'HTime'
        },
        {
          name: 'DNSHostName'
        },
        {
          name: 'Manufacturer'
        },
        {
          name: 'Model'
        },
        {
          name: 'IPAddress'
        },
        {
          name: 'UserName'
        },
        {
          name: 'UName'
        },
        {
          type: 'float',
          name: 'TotalPhysicalMemory'
        },
        {
          name: 'PM'
        }
      ]
    },
    info: {
      proxy: {
        type: 'ajax',
        reader: {
          type: 'json'
        }
      },
      fields: [
        {
          name: 'id'
        }
      ]
    }
  }

});