/*
 * File: app/view/CadastErrors/EngEdit.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.CadastErrors.EngEdit', {
  extend: 'Ext.window.Window',
  alias: 'widget.cadasterrors.engedit',

  requires: [
    'Portal.view.CadastErrors.EngEditViewModel',
    'Ext.form.Panel',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.form.field.Text',
    'Ext.form.field.Hidden'
  ],

  viewModel: {
    type: 'cadasterrors.engedit'
  },
  modal: true,
  height: 210,
  width: 532,
  layout: 'fit',
  title: 'Кадастровый инженер',
  defaultListenerScope: true,

  items: [
    {
      xtype: 'form',
      reference: 'form',
      bodyPadding: 10,
      url: 'data/CadastErrors/Engineer-edit.php',
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'container',
              padding: 10,
              items: [
                {
                  xtype: 'button',
                  formBind: true,
                  iconCls: 'dialog-save',
                  text: 'Сохранить',
                  listeners: {
                    click: 'onSave'
                  }
                },
                {
                  xtype: 'button',
                  iconCls: 'dialog-cancel',
                  text: 'Отмена',
                  listeners: {
                    click: 'onCancelClick'
                  }
                }
              ]
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Фамилия',
          name: 'Fm',
          allowBlank: false
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Имя',
          name: 'Im',
          allowBlank: false
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: 'Отчество',
          name: 'Ot',
          allowBlank: false
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          fieldLabel: '№ аттетстата',
          name: 'AttNumber',
          allowBlank: false
        },
        {
          xtype: 'hiddenfield',
          anchor: '100%',
          fieldLabel: 'Label',
          name: 'id'
        }
      ]
    }
  ],

  onSave: function(button, e, eOpts) {
    var me=this,f=me.down('form'),st=me.scope.getStore('engineers');
    if(f.isValid()){
      f.submit({
        success:function(fp,o) {
          console.log(o.result);
          st.reload();
          me.close();
        },
        failure:function(fp,o) {
          alert(o.result);
        }
      });
    }
  },

  onCancelClick: function(button, e, eOpts) {
    this.close();
  }

});