/*
 * File: app/view/admin_group/Edit1ViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.admin_group.Edit1ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.admin_groupedit1',

    onBtnAdminGroupEdit1SaveClick: function(button, e, eOpts) {
        var me = this,
            form = me.lookupReference('formEdit'),
            values = form.getValues(),
            store = Ext.getStore(values.store);

        if (form.isValid()) {
            me.getView().mask('Подождите...');

            Ext.Ajax.request({
                url: values.url,
                params: values,
                success: function(r) {
                    store.load();
                },
                failure: function(r) {
                    Ext.Msg.alert('Failed', r.result.msg);
                }
            });
            me.getView().unmask();
            me.getView().close();
        }
    },

    onBtnAdminGroupEdit1CancelClick: function(button, e, eOpts) {
        this.getView().close();
    }

});
