/*
 * File: app/view/certManager/main.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.certManager.main', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.certmanagermain',

	requires: [
		'Portal.view.certManager.mainViewModel',
		'Portal.view.certManager.mainViewController',
		'Ext.grid.Panel',
		'Ext.grid.column.RowNumberer',
		'Ext.grid.column.Action',
		'Ext.grid.column.Date',
		'Ext.view.Table',
		'Ext.toolbar.Toolbar',
		'Ext.button.Button',
		'Ext.XTemplate'
	],

	controller: 'certmanager.main',
	viewModel: {
		type: 'certmanager.main'
	},
	height: 461,
	width: 555,
	layout: 'border',
	title: 'My Panel',

	items: [
		{
			xtype: 'gridpanel',
			region: 'center',
			bind: {
				store: '{main}'
			},
			columns: [
				{
					xtype: 'rownumberer'
				},
				{
					xtype: 'actioncolumn',
					renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
						if(value>0){this.items[0].iconCls='icon-flag-blue';}
						else{this.items[0].iconCls='icon-flag-green';}
					},
					dataIndex: 'is_root',
					width: 40,
					sortable: true,
					text: 'root'
				},
				{
					xtype: 'gridcolumn',
					text: 'Действителен',
					columns: [
						{
							xtype: 'datecolumn',
							dataIndex: 'validFrom',
							text: 'С',
							format: 'Y-m-d'
						},
						{
							xtype: 'datecolumn',
							dataIndex: 'validTo',
							text: 'По',
							format: 'Y-m-d'
						}
					]
				},
				{
					xtype: 'gridcolumn',
					text: 'Субъект',
					columns: [
						{
							xtype: 'gridcolumn',
							dataIndex: 'subj_CN',
							text: 'CN'
						},
						{
							xtype: 'gridcolumn',
							dataIndex: 'subj_SNG',
							text: 'SNG'
						}
					]
				},
				{
					xtype: 'gridcolumn',
					text: 'УЦ',
					columns: [
						{
							xtype: 'gridcolumn',
							dataIndex: 'uc_CN',
							text: 'CN'
						},
						{
							xtype: 'gridcolumn',
							dataIndex: 'uc_O',
							text: 'O'
						}
					]
				},
				{
					xtype: 'gridcolumn',
					flex: 1,
					dataIndex: 'filepath',
					text: 'Путь к файлу'
				}
			],
			viewConfig: {
				getRowClass: function(record, rowIndex, rowParams, store) {
					var dm=moment(),dm2=moment(record.data.validTo),
						s14=moment(record.data.validTo).add(-14,'d'),
						s21=moment(record.data.validTo).add(-21,'d');
					if(moment(dm.format()).isSameOrAfter(dm2)){return "f-bold-red";}
					else
					if(moment(dm.format()).isSameOrAfter(s14)){return "f-bold-green";}
					else
					if(moment(dm.format()).isSameOrAfter(s21)){return "f-bold-blue";}
				}
			},
			dockedItems: [
				{
					xtype: 'toolbar',
					dock: 'top',
					items: [
						{
							xtype: 'button',
							iconCls: 'icon-refresh',
							text: 'Обновить таблицу',
							listeners: {
								click: 'onRefreshClick'
							}
						},
						{
							xtype: 'button',
							hidden: true,
							iconCls: 'icon-folder-explore',
							text: 'Отсканировать каталог',
							listeners: {
								click: 'onRescanClick'
							}
						}
					]
				}
			],
			listeners: {
				selectionchange: 'onGridpanelSelectionChange'
			}
		},
		{
			xtype: 'panel',
			region: 'south',
			split: true,
			reference: 'form',
			height: 187,
			scrollable: true,
			tpl: Ext.create('Ext.XTemplate', 
				'<a href=\'{filepath}\' target=\'_blank\'>{filepath}</a><br/>',
				'validFrom: {validFrom}<br/>',
				'validTo: <b>{validTo}</b><br/>',
				'<table>',
				'    <tr><td><u>Субъект:</u></td><td><u>УЦ:</u></td></tr>',
				'    <tr><td>{subj_SNG}</td><td>{uc_OU}</td></tr>',
				'    <tr><td>{subj_O}  </td><td>{uc_O}</td></tr>',
				'    <tr><td>{subj_CN} </td><td>{uc_CN}</td></tr>',
				'    <tr><td>{subj_Title}</td><td>{uc_Address}</td></tr>',
				'    <tr><td>{subj_Email}</td><td>{uc_Email}</td></tr>',
				'</table>',
				'Serial Number: {sn}',
				{
					f1: function() {

					}
				}
			),
			layout: 'form',
			title: 'Подробно'
		}
	],
	listeners: {
		activate: 'onMainActivate'
	}

});