/*
 * File: app/store/adminurl/MyTreeStore.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.adminurl.MyTreeStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'Portal.model.adminurl.urls',
    'Ext.data.proxy.Ajax'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'adminurl.MyTreeStore',
      model: 'Portal.model.adminurl.urls',
      proxy: {
        type: 'ajax',
        url: 'data/adminurl/url_admin.php'
      }
    }, cfg)]);
  }
});