/*
 * File: app/view/LoadUpr/AddPeriodViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.AddPeriodViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.loadupr.addperiod',

  onSaveClick: function(button, e, eOpts) {
    var v=this.getView(),f=v.down('form').getForm();
    if (f.isValid()) {
      f.submit({
        success:function(f,a) {
          Ext.getStore("LoadUpr.Years").reload();
          Ext.getStore("LoadUpr.Months").reload();
          //Ext.Msg.alert('Success', action.result.message);
          v.close();
        },
        failure:function(form, action) {
          //Ext.Msg.alert('Failed', action.result ? action.result.message : 'No response');
          Ext.Msg.alert('Ошибка','Проверьте правильность ввода данных!<br>Скорее всего такой период уже существует!');
        }
      });
    }
  },

  onYearChange: function(field, newValue, oldValue, eOpts) {
    Ext.getStore('LoadUpr.Months').load({params:{mode:'0',years:newValue,list:'short'}});
  },

  onWindowAfterRender: function(component, eOpts) {
    var td=new Date();
    this.getReferences().form.getForm().setValues({years:td.getFullYear()});
  }

});
