/*
 * File: app/view/LoadUpr/InputDataViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.LoadUpr.InputDataViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.loadupr.inputdata',

  onOtdelChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences();r.cbYear.setDisabled(false);r.tbGrid.setDisabled(true);
  },

  onYearChange: function(field, newValue, oldValue, eOpts) {
    Ext.getStore("LoadUpr.Months").load({params:{mode:'0',years:newValue,list:'short2'}});
    var r=this.getReferences();r.cbMonth.setDisabled(false);r.tbGrid.setDisabled(true);
  },

  onMonthChange: function(field, newValue, oldValue, eOpts) {
    var r=this.getReferences();r.btSay.setDisabled(false);r.tbGrid.setDisabled(true);
  },

  onSayClick: function(button, e, eOpts) {
    var r=this.getReferences();Y=r.cbYear.getValue();O=r.cbOtdel.getValue();M=r.cbMonth.getValue();
    this.getViewModel().getStore('data').load({params:{otdel:O,years:Y,months:M}});
    r.tbGrid.setDisabled(false);
  },

  onWindowAfterRender: function(component, eOpts) {
    this.getReferences().tbGrid.setDisabled(true);
  }

});
