/*
 * File: app/view/adminurl/addWindowViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.adminurl.addWindowViewModel', {
  extend: 'Ext.app.ViewModel',
  alias: 'viewmodel.adminurladdwindow',

  requires: [
    'Ext.data.Store',
    'Ext.data.proxy.Memory'
  ],

  stores: {
    'adminurl.urls': {
      model: 'Portal.model.adminurl.urls',
      data: [
        {
          name: 'iusto',
          url: 'reprehenderit',
          coment: 'vel'
        },
        {
          name: 'aut',
          url: 'quis',
          coment: 'vero'
        },
        {
          name: 'iure',
          url: 'maiores',
          coment: 'facere'
        },
        {
          name: 'nihil',
          url: 'quia',
          coment: 'voluptatem'
        },
        {
          name: 'tenetur',
          url: 'placeat',
          coment: 'et'
        },
        {
          name: 'eum',
          url: 'maiores',
          coment: 'itaque'
        },
        {
          name: 'sint',
          url: 'non',
          coment: 'iusto'
        },
        {
          name: 'vel',
          url: 'quo',
          coment: 'error'
        },
        {
          name: 'qui',
          url: 'quas',
          coment: 'exercitationem'
        },
        {
          name: 'ratione',
          url: 'laboriosam',
          coment: 'molestias'
        },
        {
          name: 'debitis',
          url: 'labore',
          coment: 'nulla'
        },
        {
          name: 'quibusdam',
          url: 'sed',
          coment: 'quaerat'
        },
        {
          name: 'quo',
          url: 'hic',
          coment: 'aut'
        },
        {
          name: 'consequuntur',
          url: 'neque',
          coment: 'ut'
        },
        {
          name: 'molestiae',
          url: 'quia',
          coment: 'quia'
        },
        {
          name: 'dolor',
          url: 'non',
          coment: 'incidunt'
        },
        {
          name: 'vitae',
          url: 'accusantium',
          coment: 'aspernatur'
        },
        {
          name: 'quo',
          url: 'velit',
          coment: 'voluptas'
        },
        {
          name: 'cum',
          url: 'maiores',
          coment: 'enim'
        },
        {
          name: 'accusamus',
          url: 'deleniti',
          coment: 'et'
        },
        {
          name: 'ab',
          url: 'odit',
          coment: 'hic'
        },
        {
          name: 'rerum',
          url: 'voluptatibus',
          coment: 'consequatur'
        },
        {
          name: 'perferendis',
          url: 'impedit',
          coment: 'illo'
        },
        {
          name: 'fuga',
          url: 'fugiat',
          coment: 'non'
        },
        {
          name: 'impedit',
          url: 'deserunt',
          coment: 'earum'
        },
        {
          name: 'est',
          url: 'sed',
          coment: 'ipsa'
        },
        {
          name: 'placeat',
          url: 'velit',
          coment: 'quia'
        },
        {
          name: 'voluptas',
          url: 'et',
          coment: 'numquam'
        },
        {
          name: 'perspiciatis',
          url: 'consequuntur',
          coment: 'quasi'
        },
        {
          name: 'similique',
          url: 'totam',
          coment: 'perferendis'
        }
      ],
      proxy: {
        type: 'memory'
      }
    }
  }

});