/*
 * File: app/view/adminurl/mainwindowViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.adminurl.mainwindowViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.adminurlmainwindow',

  onBaton_adminurl_newClick: function(button, e, eOpts) {
    var addWindow = Ext.create('Portal.view.adminurl.addWindow').show();
    addWindow.getReferences().form.getForm().setValues({
      recordid:0,
      flag:0
    });
  },

  onBtnAdminUrlRefreshClick: function(button, e, eOpts) {
    Ext.getStore('adminurl.MyTreeStore').load();
  },

  onAppadminurlAfterRender: function(component, eOpts) {
    //Ext.getStore('adminurl.MyTreeStore').load();
  }

});
