/*
 * File: app/model/FarmGZN/main.js
 * Date: Mon Jan 29 2018 13:31:30 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.model.FarmGZN.main', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.field.Date',
    'Ext.data.field.Number',
    'Ext.data.field.Boolean'
  ],

  fields: [
    {
      type: 'int',
      name: 'id'
    },
    {
      name: 'subject'
    },
    {
      name: 'cad_num'
    },
    {
      name: 'address'
    },
    {
      name: 'otdel'
    },
    {
      name: 'job'
    },
    {
      name: 'prov_form_1'
    },
    {
      name: 'prov_form_2'
    },
    {
      type: 'date',
      name: 'prov_date_end'
    },
    {
      type: 'date',
      name: 'prov_akt_date'
    },
    {
      name: 'prov_akt_num'
    },
    {
      type: 'date',
      name: 'prov_pred_date'
    },
    {
      name: 'prov_pred_num'
    },
    {
      type: 'date',
      name: 'prov_pred_srok'
    },
    {
      name: 'error_vid'
    },
    {
      name: 'oborot'
    },
    {
      type: 'float',
      name: 'area'
    },
    {
      type: 'boolean',
      name: 'error_type'
    },
    {
      name: 'organ'
    },
    {
      type: 'date',
      name: 'edoc_date'
    },
    {
      name: 'edoc_num'
    },
    {
      type: 'date',
      name: 'dateIn'
    },
    {
      name: 'user_id'
    },
    {
      type: 'date',
      name: 'update_date'
    },
    {
      name: 'user_fio'
    },
    {
      name: 'update_user'
    }
  ]
});