/*
 * File: app/controller/admin_group/admin_group.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.controller.admin_group.admin_group', {
    extend: 'Ext.app.Controller',

    models: [
        'admin_group.group',
        'admin_group.lavels',
        'admin_group.clearmodel',
        'admin_group.group_main'
    ],
    stores: [
        'admin_group.group',
        'admin_group.lavels',
        'admin_group.clearstore',
        'admin_group.group_main',
        'admin_group.group_main_list',
        'admin_group.group_app'
    ],
    views: [
        'admin_group.admin_group',
        'admin_group.Edit1'
    ]
});
