/*
 * File: app/view/portal/PVDstat.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtDesktop.view.portal.PVDstat', {
    extend: 'Ext.window.Window',
    alias: 'widget.portalpvdstat',

    requires: [
        'ExtDesktop.view.portal.PVDstatViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.container.ButtonGroup',
        'Ext.form.field.ComboBox',
        'Ext.form.Label',
        'Ext.form.field.Date',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.RowNumberer',
        'Ext.tab.Tab'
    ],

    viewModel: {
        type: 'portalpvdstat'
    },
    autoShow: true,
    height: 453,
    width: 646,
    layout: 'fit',
    title: 'ПВД статистика',
    maximizable: true,
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'buttongroup',
                    height: 74,
                    title: 'Тип отчета',
                    columns: 1,
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'TypeReport',
                            itemId: 'TypeReport',
                            width: 205,
                            displayField: 'name',
                            store: 'portal.PVDstat_TypeReport',
                            valueField: 'id',
                            valueNotFoundText: 'тип отчета'
                        },
                        {
                            xtype: 'label',
                            html: '<a href="http://sp.rosreestr.ru:8082/uit/Lists/2015/EditForm.aspx?ID=9&Source=http%3A%2F%2Fsp.rosreestr.ru%3A8082%2Fuit%2FLists%2F2015%2FAllItems.aspx" target="blank">Ссылка на отчет</a>'
                        }
                    ]
                },
                {
                    xtype: 'buttongroup',
                    height: 74,
                    width: 220,
                    collapsed: false,
                    title: 'Период',
                    columns: 1,
                    items: [
                        {
                            xtype: 'datefield',
                            id: 'DateBegin',
                            itemId: 'DateBegin',
                            padding: '0 5 0 5',
                            fieldLabel: 'Начало',
                            labelWidth: 50,
                            format: 'd/m/Y'
                        },
                        {
                            xtype: 'datefield',
                            id: 'DateEnd',
                            itemId: 'DateEnd',
                            padding: '0 5 0 5',
                            fieldLabel: 'Конец',
                            labelWidth: 50,
                            format: 'd/m/Y'
                        }
                    ]
                },
                {
                    xtype: 'buttongroup',
                    height: 74,
                    width: 103,
                    title: 'Действия',
                    columns: 1,
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'doReport',
                            itemId: 'doReport',
                            width: 80,
                            iconCls: 'icon-report',
                            text: 'Отчетик',
                            listeners: {
                                click: 'onDoReportClick'
                            }
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            text: 'Вывести в Excel'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'print',
                            itemId: 'print',
                            width: 80,
                            iconCls: 'icon-printer',
                            text: 'Печать'
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'tabpanel',
            id: 'mainTab',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Отчет',
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'mGrid',
                            itemId: 'mGrid',
                            title: 'Таблица отчета',
                            store: 'module.PVDstat_report01',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    width: 69,
                                    dataIndex: 'ID_PROC',
                                    text: 'ID_PROC'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'TEXT',
                                    text: 'Наименование',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 67,
                                    dataIndex: 'CALC',
                                    text: 'Кол-во'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 77,
                                    dataIndex: 'DB',
                                    text: 'С'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 77,
                                    dataIndex: 'DE',
                                    text: 'По'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    id: 'tabServers',
                    loader: {
                        url: 'data/pvd_get_data.html',
                        contentType: 'html'
                    },
                    title: 'Отчет о загрузке данных с серверов ПВД'
                }
            ]
        }
    ],

    onDoReportClick: function(button, e, eOpts) {
        var TypeReport = Ext.getCmp('TypeReport').getValue();
        var DateBegin = Ext.getCmp('DateBegin').getValue();
        var DateEnd = Ext.getCmp('DateEnd').getValue();
        //console.log(TypeReport+' '+Ext.Date.format(DateBegin,'d.m.Y')+' '+Ext.Date.format(DateEnd,'d.m.Y'));

        if(TypeReport && DateBegin && DateEnd){

            switch (TypeReport) {
            case '0':
                var tabPanel = Ext.getCmp('mainTab');
                tabPanel.setActiveTab(0);
                var gridStore = Ext.getStore('module.PVDstat_report01');
                gridStore.load({
                    params: {
                        db: Ext.Date.format(DateBegin,'d.m.Y'),
                        de: Ext.Date.format(DateEnd,'d.m.Y')
                    }
                });
            break;
            case '1':
                window.open('/apps/PVDstat/data/PVDstat_excel01.php?db='+Ext.Date.format(DateBegin,'d.m.Y')+'&de='+Ext.Date.format(DateEnd,'d.m.Y'));
                break;
            }
        }
    }

});