/*
 * File: app/store/GKUstop/main.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.GKUstop.main', {
  extend: 'Ext.data.Store',

  requires: [
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.field.Date'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      pageSize: 0,
      storeId: 'GKUstop.main',
      proxy: {
        type: 'ajax',
        url: 'data/GKUstop/main-list.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'zayav'
        },
        {
          type: 'date',
          name: 'zayav_date',
          dateFormat: 'Y-m-d'
        },
        {
          name: 'ONvid'
        },
        {
          name: 'zayav_type'
        },
        {
          name: 'charc'
        },
        {
          type: 'date',
          name: 'KU_date_uchet',
          dateFormat: 'Y-m-d'
        },
        {
          type: 'date',
          name: 'KU_date_stop',
          dateFormat: 'Y-m-d'
        },
        {
          type: 'date',
          name: 'KU_date_none',
          dateFormat: 'Y-m-d'
        },
        {
          name: 'KU_FZ'
        },
        {
          name: 'KU_treb'
        },
        {
          name: 'CadEngineer'
        },
        {
          name: 'KU_user_id'
        },
        {
          name: 'KU_user_fio'
        },
        {
          name: 'KU_user_update'
        },
        {
          type: 'date',
          name: 'RR_date_uchet',
          dateFormat: 'Y-m-d'
        },
        {
          type: 'date',
          name: 'RR_date_stop',
          dateFormat: 'Y-m-d'
        },
        {
          type: 'date',
          name: 'RR_date_none',
          dateFormat: 'Y-m-d'
        },
        {
          name: 'RR_FZ'
        },
        {
          name: 'RR_treb'
        },
        {
          name: 'RR_refer'
        },
        {
          name: 'RR_user_id'
        },
        {
          name: 'RR_user_fio'
        },
        {
          name: 'RR_user_update'
        },
        {
          name: 'zayav_type_N'
        },
        {
          name: 'ONvid_N'
        },
        {
          name: 'CadEngineer_N'
        },
        {
          name: 'KU_refer'
        }
      ]
    }, cfg)]);
  }
});