/*
 * File: app/store/FarmGZN/PF1.js
 * Date: Mon Jan 29 2018 16:11:48 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.FarmGZN.PF1', {
  extend: 'Ext.data.Store',

  requires: [
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.field.Field'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'FarmGZN.PF1',
      proxy: {
        type: 'ajax',
        url: 'data/FarmGZN/pf1.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    }, cfg)]);
  }
});