/*
 * File: app/view/ScanDocs/Tom.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ScanDocs.Tom', {
  extend: 'Ext.window.Window',
  alias: 'widget.scandocs.tom',

  requires: [
    'Portal.view.ScanDocs.TomViewModel',
    'Portal.view.ScanDocs.TomViewController',
    'Ext.grid.Panel',
    'Ext.grid.column.Number',
    'Ext.form.field.Number',
    'Ext.grid.column.Date',
    'Ext.view.Table',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.grid.plugin.RowEditing'
  ],

  controller: 'scandocs.tom',
  viewModel: {
    type: 'scandocs.tom'
  },
  modal: true,
  height: 286,
  width: 574,
  layout: 'fit',
  title: 'My Window',
  maximizable: true,

  items: [
    {
      xtype: 'gridpanel',
      reference: 'grid',
      bind: {
        store: '{toms}'
      },
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'name',
          text: 'Том'
        },
        {
          xtype: 'numbercolumn',
          width: 75,
          dataIndex: 'cnt_lists',
          text: 'Листов',
          format: '0',
          editor: {
            xtype: 'numberfield',
            minValue: 0
          }
        },
        {
          xtype: 'datecolumn',
          dataIndex: 'cdate',
          text: 'Учетная дата',
          format: 'Y-m-d'
        },
        {
          xtype: 'numbercolumn',
          dataIndex: 'cyear',
          text: 'За год',
          format: '0'
        },
        {
          xtype: 'gridcolumn',
          flex: 1,
          dataIndex: 'user_fio',
          text: 'Кто внес'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'button',
              iconCls: 'icon-add',
              text: 'Добавить',
              listeners: {
                click: 'onAdd'
              }
            },
            {
              xtype: 'button',
              reference: 'btnDel',
              iconCls: 'icon-delete',
              text: 'Удалить',
              listeners: {
                click: 'onDel'
              }
            }
          ]
        }
      ],
      plugins: [
        {
          ptype: 'rowediting'
        }
      ]
    }
  ]

});