/*
 * File: app/view/HW_PC/mainViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.HW_PC.mainViewController', {
  extend: 'Ext.app.ViewController',
  alias: 'controller.hw_pc.main',

  onGetXmlClick: function(button, e, eOpts) {
    /*var y=this.getReferences().year.getValue();*/
    Ext.Ajax.request({
      url: 'data/HW_PC/get4xml.php',
      success: function(r,o) {
        //var obj = Ext.decode(r.responseText);
        //console.dir(r);
        this.getViewModel().getStore("main").reload();
      },
      failure: function(r,o) {
        console.log(r);
      }
    });
  },

  onRefreshClick: function(button, e, eOpts) {
    this.getViewModel().getStore("main").reload();
  },

  onDeleteClick: function(button, e, eOpts) {
    Portal.util.Util.deleteRecord2(
    this.getReferences().mainGrid.getSelection()[0],
    this.getViewModel().getStore("main"),
    'data/HW_PC/delete.php');
  },

  onGridSelectionChange: function(model, selected, eOpts) {
    var ref=this.getReferences();
    if(selected.length){
      Ext.Ajax.request({
        url:'data/HW_PC/info.php',
        params:{id:selected[0].data.id},
        success:function(r){
          ref.DetailInfo.update(r.responseText);
        }
      });
    }
    ref.btnDel.setDisabled(selected.length===0);
  },

  onAfterRender: function(component, eOpts) {
    this.getViewModel().getStore("main").load();
  }

});
