/*
 * File: app/view/FarmGZN/EditViewModel.js
 * Date: Mon Jan 29 2018 12:38:08 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.FarmGZN.EditViewModel', {
  extend: 'Ext.app.ViewModel',
  alias: 'viewmodel.farmgzn.edit',

  requires: [
    'Ext.data.Store',
    'Ext.data.field.Field',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json'
  ],

  stores: {
    prov_form_2: {
      data: [
        {
          id: 1,
          name: 'Плановая'
        },
        {
          id: 2,
          name: 'Внелановая'
        }
      ],
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    },
    prov_form_1: {
      data: [
        {
          id: 1,
          name: 'Выездная'
        },
        {
          id: 2,
          name: 'Документарная'
        }
      ],
      proxy: {
        type: 'ajax',
        reader: {
          type: 'json'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    },
    organ1: {
      proxy: {
        type: 'ajax',
        url: 'data/FarmGZN/organ1.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    },
    organ2: {
      proxy: {
        type: 'ajax',
        url: 'data/FarmGZN/organ2.php',
        reader: {
          type: 'json',
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    },
    jobs: {
      data: [
        {
          id: '1',
          name: 'Проверка'
        },
        {
          id: '2',
          name: 'Административное обследование'
        },
        {
          id: '3',
          name: 'Иное'
        }
      ],
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        }
      ]
    }
  }

});