/*
 * File: app/view/FarmGZN/main.js
 * Date: Wed Jan 31 2018 13:16:48 GMT+0300 (RTZ 2 (зима))
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.FarmGZN.main', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.farmgzn',

  requires: [
    'Portal.view.FarmGZN.mainViewModel',
    'Portal.view.FarmGZN.mainViewController',
    'Ext.toolbar.Toolbar',
    'Ext.button.Button',
    'Ext.grid.Panel',
    'Ext.grid.column.RowNumberer',
    'Ext.grid.filters.filter.String',
    'Ext.grid.filters.filter.List',
    'Ext.view.Table',
    'Ext.grid.column.Date',
    'Ext.grid.filters.filter.Date',
    'Ext.grid.column.Action',
    'Ext.grid.filters.Filters'
  ],

  controller: 'farmgzn.main',
  viewModel: {
    type: 'farmgzn.main'
  },
  height: 565,
  width: 1218,
  layout: 'border',
  title: 'My Panel',

  dockedItems: [
    {
      xtype: 'toolbar',
      dock: 'top',
      items: [
        {
          xtype: 'button',
          reference: 'btnAdd',
          iconCls: 'icon-add',
          text: 'Добавить',
          listeners: {
            click: 'onAddClick'
          }
        },
        {
          xtype: 'button',
          reference: 'btnEdit',
          disabled: true,
          hidden: true,
          iconCls: 'icon-edit',
          text: 'Редактировать',
          listeners: {
            click: 'onEditClick'
          }
        },
        {
          xtype: 'button',
          iconCls: 'icon-refresh',
          text: 'Обновить',
          listeners: {
            click: 'onRefresh'
          }
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'gridpanel',
      region: 'center',
      reference: 'grid',
      stateful: true,
      stateId: 'FarmGZNgrid',
      defaults: {
        align: 'center'
      },
      store: 'FarmGZN.main',
      columns: [
        {
          xtype: 'rownumberer'
        },
        {
          xtype: 'gridcolumn',
          width: 123,
          dataIndex: 'cad_num',
          locked: true,
          text: 'КН ЗУ',
          filter: {
            type: 'string'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'address',
          text: 'Адрес ЗУ',
          filter: {
            type: 'string'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'otdel',
          text: 'Тер.отдел,<br>проводивший<br>проверку',
          filter: {
            type: 'list'
          }
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'job',
          text: 'Наименование<br>проведенного<br>мероприятия'
        },
        {
          xtype: 'gridcolumn',
          text: 'Форма проведения проверки',
          columns: [
            {
              xtype: 'gridcolumn',
              align: 'center',
              dataIndex: 'prov_form_1',
              text: 'выезд./<br>докум.',
              filter: {
                type: 'list'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'prov_form_2',
              text: 'план./<br>внеплан.',
              filter: {
                type: 'list'
              }
            }
          ]
        },
        {
          xtype: 'datecolumn',
          width: 75,
          dataIndex: 'prov_date_end',
          text: 'Дата<br>окончания<br>проверки',
          format: 'Y-m-d',
          filter: {
            type: 'date'
          }
        },
        {
          xtype: 'gridcolumn',
          text: 'Реквизиты акта проверки об<br>устранении нарушений',
          columns: [
            {
              xtype: 'datecolumn',
              width: 75,
              dataIndex: 'prov_akt_date',
              text: 'Дата',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'prov_akt_num',
              text: 'Номер',
              filter: {
                type: 'string'
              }
            }
          ]
        },
        {
          xtype: 'gridcolumn',
          text: 'Реквизиты предписания об<br>устранении нарушений',
          columns: [
            {
              xtype: 'datecolumn',
              width: 75,
              dataIndex: 'prov_pred_date',
              text: 'Дата',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'prov_pred_num',
              text: 'Номер',
              filter: {
                type: 'string'
              }
            },
            {
              xtype: 'datecolumn',
              width: 75,
              dataIndex: 'prov_pred_srok',
              text: 'Срок',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            }
          ]
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'error_vid',
          text: 'Вид выявленного<br>правонарушения'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'oborot',
          text: 'Оборот'
        },
        {
          xtype: 'gridcolumn',
          align: 'end',
          dataIndex: 'area',
          text: 'Площадь<br>нарушения,<br>кв. м'
        },
        {
          xtype: 'actioncolumn',
          getClass: function(v, metadata, r, rowIndex, colIndex, store) {
            if(r.data.error_type){return "icon-flag-green";}
            else{return "icon-flag-red";}
          },
          align: 'center',
          dataIndex: 'error_type',
          text: 'Отметка об<br>устранении<br>правонарушения<br>на дату<br>представления<br>информации<br>в Росреестр'
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'organ',
          text: 'Орган, принявший<br>решение об устранении'
        },
        {
          xtype: 'gridcolumn',
          text: 'Документ об<br>устранении нарушений',
          columns: [
            {
              xtype: 'datecolumn',
              dataIndex: 'edoc_date',
              text: 'Дата',
              format: 'Y-m-d',
              filter: {
                type: 'date'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'edoc_num',
              text: 'Номер',
              filter: {
                type: 'string'
              }
            }
          ]
        },
        {
          xtype: 'gridcolumn',
          dataIndex: 'user_fio',
          text: 'Специалист,<br>предоставивший<br>информацию'
        },
        {
          xtype: 'datecolumn',
          dataIndex: 'dateIn',
          text: 'Дата<br>внесения<br>сведений',
          format: 'Y-m-d',
          filter: {
            type: 'date'
          }
        }
      ],
      viewConfig: {
        getRowClass: function(record, rowIndex, rowParams, store) {

        }
      },
      listeners: {
        selectionchange: 'onGridSelectionChange'
      },
      plugins: [
        {
          ptype: 'gridfilters'
        }
      ]
    },
    {
      xtype: 'panel',
      region: 'south',
      reference: 'info',
      height: 64,
      padding: 10
    }
  ],
  listeners: {
    afterrender: 'onAfterRender'
  }

});