/*
 * File: app/view/ScanDocs/TomViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.ScanDocs.TomViewModel', {
  extend: 'Ext.app.ViewModel',
  alias: 'viewmodel.scandocs.tom',

  requires: [
    'Ext.data.Store',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json',
    'Ext.data.writer.Json',
    'Ext.data.field.Integer'
  ],

  stores: {
    toms: {
      autoSync: true,
      proxy: {
        type: 'ajax',
        api: {
          create: 'data/ScanDocs/getTomWrite.php',
          read: 'data/ScanDocs/getTom.php',
          update: 'data/ScanDocs/getTomWrite.php',
          destroy: 'data/ScanDocs/getTomDestroy.php'
        },
        reader: {
          type: 'json',
          rootProperty: 'data'
        },
        writer: {
          type: 'json',
          writeAllFields: true,
          encode: true,
          rootProperty: 'data'
        }
      },
      fields: [
        {
          name: 'id'
        },
        {
          name: 'name'
        },
        {
          type: 'int',
          name: 'cnt_lists'
        },
        {
          name: 'cdate'
        },
        {
          name: 'cyear'
        },
        {
          name: 'timeUpdate'
        },
        {
          name: 'user_id'
        },
        {
          name: 'user_fio'
        }
      ]
    }
  }

});